### ISSUE TITLE
[QUESTION] - storage limits?

### ISSUE THREAD

**Issue by Canta** [sql-js/sql.js#20]
Hi there.

Sorry if it's not the place for a question, i just didn't found any other place for it.

I'm working in a web app that manages lots of documents. Those documents can be text files, pdf files, LibreOffice texts, mp3 files, images, and so on. I do stuff to the documents, and then store the results. And i want to do all that client-side, using only javascript.

JS seems to be mature enough for an app like that, as lots of libraries already let me do every job and everything works pretty good actually. However, there's a critical point on the current state of JS development regarding storage. My app will most likely use a lot of storage: lots in size, and lots in time. And after testing the current APIs for local storage, none of them was ok for my project.

So... i found sql.js, and it seems great. I'll just open and save sqlite dbs using file and blob urls, and that would give me any storage i could need. However, i wonder how does this sqlite port works with the js db. Is it an in-memory blob? It's some file object on the local storage? Something else? 
I ask this because i'm concerned about the possible limits for a DB using sql.js. Did anyone tested it with some >500MB database?

Thanks.
And thanks for this great project too, btw :)

**Comment by beatak** [comment]
I'm running `sql.js` on `node`, the maximum db size seems to be around 120MB even with the maximum memory allocation.  This is totally not objective number at all, but just you know…

**Comment by lovasoa** [comment]
Thank you.

**Comment by tracker1** [comment]
You may do slightly better if you use the command-line flag to expose GC and collect manually after update operations...  I've found that when you're working with a lot of data (migrating large csv/xml) that memory usage can get unweildy or will just fail.. some simple tests I ran dropped out around 1GB of memory used in node (with arrays of arrays, not sql.js).

There may be some limits to the number of handles/references allowed altogether in v8...  

For others working on adjusting a lot of data, I'd suggest using a separate Message Queue system, and have one node process pushing into a queue, and one or more others working from it... This has been the most reliable option for me in dealing with a lot of data/records
