### ISSUE TITLE
Build failing with coffee 2.4.1

### ISSUE THREAD

**Issue by rogerfar** [sql-js/sql.js#291]
I'm trying to build master with coffee `2.4.1` and it's failing on the following:

```
/tmp/tmpfY2gMS.cl.js:51: ERROR - This language feature is only supported for ECMASCRIPT6 mode or better: class.
Statement = class Statement {
            ^
```

I think it's missing the `--language_in ECMASCRIPT6 --language_out ES5` flag in the emcc build path, as shown in #240

**Comment by lovasoa** [comment]
I'm closing this since we moved from coffee to javascript
