### ISSUE TITLE
Support with Sqllite in android

### ISSUE THREAD

**Issue by jindalAnuj** [sql-js/sql.js#300]
Hi there . I am pretty new to SQL . 
Can anyone help me with my question ?

Is it possible to use this library in android with html and javascript (in web-view ) and my db as Sqllite ( default android Db)
If not is there any other way 

Thanks in advance:relaxed:

**Comment by brodybits** [comment]
sql.js should work in any web view that follows the HTML5 and JavaScript standards to a *reasonable* extent (should not have to be too strict, should not have to be too recent)

The one caveat is that sql.js does not directly support anything beyond memory filesystem. It is possible to save and load from disk but I think this should not be considered ACID.
