### ISSUE TITLE
WASM fails with: "failed to asynchronously prepare wasm"

### ISSUE THREAD

**Issue by kolbasa** [sql-js/sql.js#308]
I get an error with `sql-wasm.js` while `sql-asm.js` works fine.
```
both async and sync fetching of the wasm failed
failed to asynchronously prepare wasm: abort(both async and sync fetching of the wasm failed) at Error
    at jsStackTrace (/node_modules/sql.js/dist/sql-wasm-debug.js:2762:17)
    at jsStackTrace (/node_modules/sql.js/dist/sql-wasm-debug.js:2762:17)
```

My environment:
* sql.js: `v1.0.1`
* Node.js: `v8.16.0`
* MacOS: `v10.14.6`

My code:
```javascript
require('sql.js'); // fails
require('../node_modules/sql.js/dist/sql-wasm.js'); // fails
require('../node_modules/sql.js/dist/sql-asm.js');  // works
```

**Comment by lovasoa** [comment]
I am unable to reproduce the error with node 12.12.0 on macOS 10.14.6:

```
$ npm i sql.js
+ sql.js@1.0.1
added 1 package from 6 contributors and audited 1 package in 1.787s
$ echo "require('sql.js')().then(_ => console.log('success'))" > test.js
$ node test.js
success
```

**Comment by lovasoa** [comment]
Out of simple curiosity, why would you use sql.js instead of a native SQLite module on node ?

**Comment by kolbasa** [comment]
Thank you for your prompt reply.

I'm using sql.js as a fallback for the [cordova-sqlite-storage](https://github.com/xpbrew/cordova-sqlite-storage)-plugin in an angular-app. This works wonderfully.

But I also need tests for it. These are based on [mocha](https://mochajs.org/index.html) and [jsdom](https://github.com/jsdom/jsdom) for node.js.

I kept looking for a solution. I know now that it is caused by jsdom.

The updated example code is:
`package.json`:
```
{
  "dependencies": {
    "jsdom": "^15.2.1",
    "sql.js": "^1.0.1"
  }
}
```
`main.js`:
```javascript
const {JSDOM} = require('jsdom');

global.document = new JSDOM('<!DOCTYPE html><p>Hello world</p>');
global.window = global.document.window;

require('sql.js')(); // fails
require('./node_modules/sql.js/dist/sql-wasm.js')(); // fails
require('./node_modules/sql.js/dist/sql-asm.js')(); // works
```

I have no big drawback now. I was just hoping to speed up my tests.
You are welcome to close the issue if it is not directly related to sql.js :).

**Comment by ncortines** [comment]
Hi,

I encountered the same problem when upgrading to 1.0.1

My use case is slightly different though. I'm using browserify to bundle the require/node version, to then run tests with puppeteer on chromium.

This use case works fine on 0.5.0.

Thanks,
Juan

**Comment by lovasoa** [comment]
0.5.0 did not use wasm. I guess your error is due to the fact you did not provide a correct path to your assets in the `initSqlJs` options:

```js
initSqlJs({ locateFile: filename => `/path/to/assets/${filename}` })
```

**Comment by kolbasa** [comment]
I updated from `v1.0.1` to `v1.3.0`.
The problem no longer exists. I can now use my tests with `sql-wasm.js` without further adjustments. And they run super fast.
Thank you!

**Comment by liu333333** [comment]
I encountered the same problem,and  my version is 1.9.0
