### ISSUE TITLE
sqlite3_column_double is lossy

### ISSUE THREAD

**Issue by AnyhowStep** [sql-js/sql.js#325]
Running the following statement,
```sql
SELECT 1.7976931348623157e+308
```

On this,
http://kripken.github.io/sql.js/examples/GUI/

Gives me this result set,

|1.7976931348623157e+308|
|--|
Infinity

-----

I know it's not supposed to be `Infinity` because of this DB Fiddle,

**Schema (SQLite v3.30)**

    

---

**Query 1**

    SELECT 1.7976931348623157e+308;

| 1.7976931348623157e+308 |
| ----------------------- |
| 1.7976931348623157e+308 |

---

[View on DB Fiddle](https://www.db-fiddle.com/f/smqdPpiHHGs2oUyJhGeWky/0)

-----

This isn't the only example of doubles being lossy for some reason unknown to me.
I've seen cases where I had decimal places being cut off, numbers being rounded up and down, etc.
Is there a workaround for this?

**Comment by AnyhowStep** [comment]
I wonder if it has to do with this flag,
https://github.com/kripken/sql.js/blob/142d9de79be98d58368b440f3160935b73ce3154/Makefile#L22

Is there a different flag that needs to be set?

**Comment by AnyhowStep** [comment]
Not quite related, but I'm not sure if I should open a new issue.

This query,
```ts
SELECT 1.7976931348623157e+308 * 1.7976931348623157e+308
```

Should return `null` (as in regular SQLite)

**Comment by lovasoa** [comment]
> ```ts
> SELECT 1.7976931348623157e+308 * 1.7976931348623157e+308
> ```
> Should return `null` (as in regular SQLite).

I just tried it on my computer : 

```
$ sqlite3 --version
3.22.0 2018-01-22 18:45:57 0c55d179733b46d8d0ba4d88e01a25e10677046ee3da1d5b1581e86726f2alt1
$ echo 'SELECT 1.7976931348623157e+308 * 1.7976931348623157e+308;' | sqlite3 
Inf
```

**Comment by AnyhowStep** [comment]
Ah, right. I forgot DB Fiddle returns results as a JSON string, and Inf, NaN, -Inf become `null`. Sorry about that

**Comment by brodybits** [comment]
> I wonder if it has to do with this flag,
> https://github.com/kripken/sql.js/blob/142d9de79be98d58368b440f3160935b73ce3154/Makefile#L22

Yes. Removing this flag does seem to resolve the issue for me, both in a new test case and in my local build of the GUI. I just proposed a new test case in draft PR #336, fix PR is coming next.
