### ISSUE TITLE
Move the project to a github organisation 

### ISSUE THREAD

**Issue by lovasoa** [sql-js/sql.js#358]
Hello @kripken ,
  I am opening this issue to discuss [moving this repository to a github organization](https://help.github.jp/enterprise/2.11/user/articles/transferring-a-repository-owned-by-your-personal-account/). Currently, the repository is on your personal account, and I cannot access its settings.
  The first thing I would like to do when I get access to the settings is adding an NPM token to the repository so that I can setup continuous deployment of the [sql.js npm module](https://www.npmjs.com/package/sql.js).
   What do you think ?

**Comment by kaizhu256** [comment]
operational note:
`github.com/sqljs` is already taken, but `github.com/sql-js` is available, and i reserved it just in case

**Comment by lovasoa** [comment]
@kaizhu256 that is very kind of you, but I think it would be better if either kripken or me were the organization owner 🙂

**Comment by kaizhu256** [comment]
invited both as owners.

**Comment by kripken** [comment]
I'm fine with anything that is good for you! Sorry I haven't had time to help maintain the project myself.

**Comment by lovasoa** [comment]
@kripken can you [transfer the repo](https://help.github.jp/enterprise/2.11/user/articles/transferring-a-repository-owned-by-your-personal-account/) to the [sql-js](https://github.com/sql-js) organization ?

**Comment by kripken** [comment]
Sure, done! And looks like it worked, reloading the page shows this is under `sql-js`.

**Comment by kaizhu256** [comment]
now it needs a logo.  anyone a semi-designer or know of one?  i'm definitely not one.

**Comment by lovasoa** [comment]
What would be nice to have in this organization is high-quality examples of integrations of sql.js with various popular build systems. I think the biggest problem of sql.js right now is that it doesn't work *out of the box*, and the distribution of wasm files has to be set up manually. I think having example projects showing how to integrate sql.js with :
 * [gulp](https://gulpjs.com/)
 * [create-react-app](https://github.com/facebook/create-react-app)
 * [webpack](https://www.npmjs.com/package/webpack)
 * [parcel](https://parceljs.org/)

would be great. What do you think ?

**Comment by lovasoa** [comment]
I am closing this ticket since the organization is created. We can open new tickets for specific topics.

**Comment by kaizhu256** [comment]
working-out-of-the-box to me means a single, prebuilt dist-file that just works with zero-config and zero-tooling, like localforage, jquery, etc.

if there's no longer a dist/ folder, can we create a github-releases-page where people can download prebuilt dists like https://github.com/electron/electron/releases?

![image](https://user-images.githubusercontent.com/280571/75789364-3149fd00-5d2f-11ea-89fb-ad24684cb192.png)

also, the dist-file names and choices are confusing for mainstream-users.  they could be renamed as follows:
```
mainstream, general-purpose use:
1. sql-wasm.wasm    (from sql-wasm.wasm)
2. sql-wasm.js      (from worker.sql-wasm.js but unminified)
3. sql-wasm.min.js  (from worker.sql-wasm.js minified)
4. sql-asm.js       (from worker.sql-asm.js but unminified)
5. sql-asm.min.js   (from worker.sql-asm.js minified)

specialized debug variant:
6. sql-wasm-debug.wasm (from sql-wasm-debug.wasm)
7. sql-wasm-debug.js   (from worker.sql-wasm-debug.js)

specialized asm memory variant
8. sql-asm-memory-growth.js (from sql-asm-memory-growth.js)
```

**Comment by lovasoa** [comment]
> if there's no longer a dist/ folder, can we create a github-releases-page where people can download prebuilt dists

We do already have that. Check https://github.com/sql-js/sql.js/releases

>  they could be renamed as follows

Check the Makefile for the build process. I'm not against name changes if we have to break backward compatibility at some point anyway. But the webworker-specific files should clearly indicate that they are meant to be used as web workers, and we do not distribute non-debug builds that are not minified.

**Comment by kaizhu256** [comment]
> We do already have that. Check https://github.com/sql-js/sql.js/releases

oh, good to know



> we do not distribute non-debug builds that are not minified

i use debug-build in production because it has good-enough performance (chrome-webworker ingests 200mb csv into sqlite3 in 30 seconds), and the unminified form is easier to hack (e.g. add `params` option when postMessaging `exec` command to worker).  the debug-binary is about 16% larger than non-debug (1.62mb vs 1.4mb).

if currently tooling disallows unminified "normal" builds, can we discourage the normal-build, and recommend the debug-build for mainstream-use instead?

```
mainstream, general-purpose use (easy to debug and modify):
1. sql-wasm.wasm          - from sql-wasm-debug.wasm
2. sql-wasm.js            - from sql-wasm-debug.js
3. sql-wasm.min.js        - from sql-wasm-debug.js        (minified)
4. sql-wasm-worker.js     - from worker.sql-wasm-debug.js
5. sql-wasm-worker.min.js - from worker.sql-wasm-debug.js (minified)

specialized, with marginal performance-boost (hard to debug):
6. sql-wasm-optimized.wasm   - from sql-wasm.wasm
7. sql-wasm-optimized.min.js - from sql-wasm.js
```

**Comment by lovasoa** [comment]
> if currently tooling disallows unminified "normal" builds, can we discourage the normal-build, and recommend the debug-build for mainstream-use instead?

I don't think that is a good idea. We do not want to encourage users to maintain their own fork of the library, and debug builds are significantly less performant.

**Comment by brodybits** [comment]
> We do not want to encourage users to maintain their own fork of the library

I do need to maintain my own fork to provide some custom functions, and some others may need to fork to get some more advanced options such as FTS4, FTS5, R-Tree, and JSON1. Spirit of open source:)

That said, I think the best way for people to do custom builds would be to make a new wrapper project that includes this one as a dependency or dev dependency. It would be nice if we could find a way to make the Makefile work more easily with custom builds. Ideas include adapting the Makefile to read env for custom build flags or moving the bulk of the Makefile into a .mk file that someone else could include to do a custom build. (I wish I had more time to work on these ideas.)

**Comment by kaizhu256** [comment]
@brodybits what if sql.js shipped 3 dist-variants simliar to debian packages nginx-lite, nginx-full, nginx-extras?

1. sqljs-lite.zip
minimal extra-features, similar to current dist

2. sqljs-full.zip (recommended for mainstream use)
has fts5, and other popular features

3. sqljs-extras.zip
everything plus kitchen-sink - hopefully includes all features in your fork.

would sqljs-extras be good-enough for power-users, so they don't need their own custom builds?
i'm not expert on sqlite-addons, so someone else's input on feasibility of sqljs-extras is appreciated.
