### ISSUE TITLE
branding - rename org to sqljs-io

### ISSUE THREAD

**Issue by kaizhu256** [sql-js/sql.js#359]
#### pros of changing org-name from sql-js to sqljs-io:
- consistent prefixing with `sqljs`, e.g.:
    - sqljs-wasm-worker-debug.js
    - https://github.com/sqljs-io/sqljs-import-csv (example org repo naming convention)
- npm namespace is not taken - https://www.npmjs.com/package/sqljs-io
- domain-name is not taken - https://sqljs.io

#### cons
- name is a little longer
- we don't want to keep changing org-name.  pick one and stick with it.

what do you think?  also other name suggestions are welcome.

**Comment by brodybits** [comment]
I would favor a different kind of solution: keep the repo here and put the homepage on sql.js.org

**Comment by kaizhu256** [comment]
i'm ok with that.

what about prefix-naming-convention?
1. sql-wasm-worker-debug.js, https://github.com/sql-js/sql-gui-library
2. sqljs-wasm-worker-debug.js, https://github.com/sql-js/sqljs-gui-library
3. sql-js-wasm-worker-debug.js, https://github.com/sql-js/sql-js-gui-library
4. sql.js-wasm-worker-debug.js, https://github.com/sql-js/sql-js-gui-library

i prefer 2 > 1 > 3 > 4

**Comment by brodybits** [comment]
> i'm ok with that.

I just opened <https://github.com/js-org/js.org/issues/3775> to start discussion of sql.js.org there, suspect it should be good since sql.js is so well-known. Normally they would need either the org name or the project name to match the "cname", not sure how strict it would have to be. (Maybe using https://github.com/sql-js/sql to host the homepage documents could be the solution, we will have to see from discussions.)

> what about prefix-naming-convention?

I would vote 1 > 3 > 4 , 2

**Comment by brodybits** [comment]
I just saw a nice response in <https://github.com/js-org/js.org/issues/3775#issuecomment-594229052>, looks like it *should* be ok. Leaving it up to you guys now. 🚀

**Comment by kaizhu256** [comment]
i'm ok with @brodybits preference for naming-convention:
1. sql-wasm-worker-debug.js, https://github.com/sql-js/sql-libraryorwhatnot

actionable item is to update Makefile to rename worker dist-files to new convention.

last call for [non] consensus before closing this issue?

**Comment by lovasoa** [comment]
This is a backward-incompatible change that I don't think we should do unless we have a good reason to.

**Comment by kaizhu256** [comment]
but we do agree to not rename the github-org?  i want to unblock #360 so @kripken can move forward with the redirect gh-pages stub (or not, but at least have that issue resolved).

**Comment by lovasoa** [comment]
> but we do agree to not rename the github-org?
yes

**Comment by kaizhu256** [comment]
closing this issue as discussion has veered off-topic with no consensus.  the original topic of renaming the org has been resolved as WON'T CHANGE.
