### ISSUE TITLE
links to kripken.github.io/sql.js are broken

### ISSUE THREAD

**Issue by kaizhu256** [sql-js/sql.js#360]
a posted solution is for @kripken to create a stub gh-pages repo redirecting to https://sql-js.github.io/sql.js/examples/GUI/ [1].  it should also include a README.md stating the site has moved here.

above solution potentially blocked by issue #359

[1] Redirecting GitHub Pages after a repository move
https://gist.github.com/domenic/1f286d415559b56d725bee51a62c24a7

**Comment by kaizhu256** [comment]
@kripken, issue is no longer blocked.  can you clone the stub repo i've created @ https://github.com/kaizhu256/sql.js.redirect to the original sql.js repo under your name?

its essentially original gh-pages branch with all .html files and README.md replaced with redirect-links

![image](https://user-images.githubusercontent.com/280571/76283165-e3218600-6267-11ea-95bc-520c891992d7.png)

i've verified the following links redirect correctly:
 - https://kaizhu256.github.io/sql.js.redirect/GUI/codemirror/mode/sql
 - https://kaizhu256.github.io/sql.js.redirect/GUI/codemirror/mode/sql/index.html
 - https://kaizhu256.github.io/sql.js.redirect/GUI
 - https://kaizhu256.github.io/sql.js.redirect/GUI/index.html
 - https://kaizhu256.github.io/sql.js.redirect/documentation/alphabetical_index.html
 - https://kaizhu256.github.io/sql.js.redirect/documentation/class/Database.html
 - https://kaizhu256.github.io/sql.js.redirect/documentation/class/Statement.html
 - https://kaizhu256.github.io/sql.js.redirect/documentation/class_list.html
 - https://kaizhu256.github.io/sql.js.redirect/documentation/coffee/api.coffee.html
 - https://kaizhu256.github.io/sql.js.redirect/documentation/extra/AUTHORS.html
 - https://kaizhu256.github.io/sql.js.redirect/documentation/extra/README.md.html
 - https://kaizhu256.github.io/sql.js.redirect/documentation/extra_list.html
 - https://kaizhu256.github.io/sql.js.redirect/documentation/file/coffee/api.coffee.html
 - https://kaizhu256.github.io/sql.js.redirect/documentation/file_list.html
 - https://kaizhu256.github.io/sql.js.redirect/documentation
 - https://kaizhu256.github.io/sql.js.redirect/documentation/index.html
 - https://kaizhu256.github.io/sql.js.redirect/documentation/method_list.html
 - https://kaizhu256.github.io/sql.js.redirect/documentation/mixin_list.html
 - https://kaizhu256.github.io/sql.js.redirect/examples/GUI
 - https://kaizhu256.github.io/sql.js.redirect/examples/GUI/index.html
 - https://kaizhu256.github.io/sql.js.redirect/examples/persistent.html
 - https://kaizhu256.github.io/sql.js.redirect/examples/repl.html
 - https://kaizhu256.github.io/sql.js.redirect/examples/requireJS.html
 - https://kaizhu256.github.io/sql.js.redirect/examples/simple.html
 - https://kaizhu256.github.io/sql.js.redirect
 - https://kaizhu256.github.io/sql.js.redirect/index.html
 - https://kaizhu256.github.io/sql.js.redirect/test/demo.html - manually fixed redirect to a broken 2nd redirect
 - https://kaizhu256.github.io/sql.js.redirect/test/sql-requireJS.html

and here are the contents of the stub gh-pages repo:
```
0.    2020-03-10 00:31:55 -0500  43851198 bytes .
1.    2019-04-26 14:45:43 -0500        64 bytes .gitignore
2.    2020-03-10 00:31:55 -0500       345 bytes GUI/codemirror/mode/sql/index.html
3.    2020-03-10 00:31:55 -0500       285 bytes GUI/index.html
4.    2020-03-10 00:31:55 -0500       101 bytes README.md
5.    2019-04-29 11:17:40 +0300  15510962 bytes dist/sql-asm-debug.js
6.    2019-04-26 14:43:59 -0500   3036913 bytes dist/sql-asm-memory-growth.js
7.    2019-04-26 14:43:59 -0500   3034879 bytes dist/sql-asm.js
8.    2019-04-26 14:43:59 -0500    245614 bytes dist/sql-wasm-debug.js
9.    2019-04-26 14:43:59 -0500   1660650 bytes dist/sql-wasm-debug.wasm
10.   2019-04-26 14:43:59 -0500     56474 bytes dist/sql-wasm.js
11.   2019-04-26 14:43:59 -0500   1450157 bytes dist/sql-wasm.wasm
12.   2019-04-26 14:43:59 -0500  15504854 bytes dist/worker.sql-asm-debug.js
13.   2019-04-26 14:43:59 -0500   3036918 bytes dist/worker.sql-asm.js
14.   2019-04-26 14:43:59 -0500    247653 bytes dist/worker.sql-wasm-debug.js
15.   2019-04-26 14:43:59 -0500     58513 bytes dist/worker.sql-wasm.js
16.   2020-03-10 00:31:55 -0500       354 bytes documentation/alphabetical_index.html
17.   2020-03-10 00:31:55 -0500       342 bytes documentation/class/Database.html
18.   2020-03-10 00:31:55 -0500       345 bytes documentation/class/Statement.html
19.   2020-03-10 00:31:55 -0500       330 bytes documentation/class_list.html
20.   2020-03-10 00:31:55 -0500       351 bytes documentation/coffee/api.coffee.html
21.   2020-03-10 00:31:55 -0500       339 bytes documentation/extra/AUTHORS.html
22.   2020-03-10 00:31:55 -0500       345 bytes documentation/extra/README.md.html
23.   2020-03-10 00:31:55 -0500       330 bytes documentation/extra_list.html
24.   2020-03-10 00:31:55 -0500       366 bytes documentation/file/coffee/api.coffee.html
25.   2020-03-10 00:31:55 -0500       327 bytes documentation/file_list.html
26.   2020-03-10 00:31:55 -0500       315 bytes documentation/index.html
27.   2020-03-10 00:31:55 -0500       333 bytes documentation/method_list.html
28.   2020-03-10 00:31:55 -0500       330 bytes documentation/mixin_list.html
29.   2020-03-10 00:31:55 -0500       312 bytes examples/GUI/index.html
30.   2020-03-10 00:31:55 -0500       315 bytes examples/persistent.html
31.   2020-03-10 00:31:55 -0500       297 bytes examples/repl.html
32.   2020-03-10 00:31:55 -0500       312 bytes examples/requireJS.html
33.   2020-03-10 00:31:55 -0500       303 bytes examples/simple.html
34.   2020-03-10 00:31:55 -0500       273 bytes index.html
35.   2020-03-10 00:31:55 -0500       285 bytes test/demo.html
36.   2020-03-10 00:31:55 -0500       312 bytes test/sql-requireJS.html
```

**Comment by kripken** [comment]
@kaizhu256 ok, clone and renamed. Did I do it right?

**Comment by kaizhu256** [comment]
Woot!  Verified http://kripken.github.io/sql.js/examples/GUI/ properly redirects.
