### ISSUE TITLE
sql.js.org website

### ISSUE THREAD

**Issue by brodycj** [sql-js/sql.js#361]
<https://github.com/js-org/js.org/issues/3775>

Would definitely be nicer than sql-js.github.io/...

I would be happy to help with this if needed.

**Comment by lovasoa** [comment]
Yes, work on the website would be welcome, thank you for proposing your help @brodybits !

I think there is quite some work:

 - cleaning up the website files that are currently mixed with the source files, and creating a `CNAME` file for js.org 
 - have a single command to build the website (including the jsdoc documentation)
 - add an action to `.github/workflows` to run that command on CI and push the result to the `gh-pages` branch

Once we have that, we can open a PR to js.org to have sql.js.org.

**Comment by lovasoa** [comment]
I created a demonstration of how to integrate sql.js with webpack at https://github.com/sql-js/react-sqljs-demo

You can use that, and move it into gh-pages if you want, @brodybits

**Comment by brodybits** [comment]
Hi @lovasoa that demo looks really nice. A couple questions & ideas:

- I would favor making the demo under MIT license, which should be more consistent with React, SQL.js, and so many other packages in the JS ecosystem.
- Nicer multi-line editor, ideally with SQL highlighting (should be pretty easy to find an existing solution that can work with React)

**Comment by lovasoa** [comment]
I updated the license.

As for the second change... Maybe there should be two demos ? 
One that is full-featured and replaces the old https://sql-js.github.io/sql.js/examples/GUI/
and one that is very short and well-commented that can be used as a template and a reference for how to integrate sql.js with a build system. I would like users to be able to go over the sources in <5mins.

**Comment by brodybits** [comment]
> one that is very short and well-commented
> [...]
> I would like users to be able to go over the sources of this demo in <5mins.

Yes, maybe with some kind of a "use this template" button like here: <https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template>

**Comment by lovasoa** [comment]
>  maybe with some kind of a "use this template" button

I did that already.

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/552629/76442405-2fcca480-63c1-11ea-9ad2-a9e4fca79d60.png">

**Comment by kaizhu256** [comment]
nice work on react-demo.

but are we gonna use react for full-feature demo?  i prefer it stays vanilla-js so people like me can clone-and-modify it w/o any extra tooling.

also have plans to add import/export csv buttons to the full-feature demo (and perhaps store/load buttons for indexeddb).

**Comment by lovasoa** [comment]
I think a majority of frontend project these days use some sort of tooling. But nothing is preventing us from having many different demos, demonstrating different usages. One of them can be one where everything is done by hand.

**Comment by lovasoa** [comment]
@brodybits : are you still working on this?

**Comment by brodybits** [comment]
Maybe later this week, if nobody else wants to take it on. My apologies.

**Comment by lovasoa** [comment]
No problem, you have no obligations here. If you change your mind, just tell me and I'll assign this to myself.

**Comment by brodybits** [comment]
👍thanks!

**Comment by lovasoa** [comment]
we're live on https://sql.js.org

**Comment by sunnykgupta** [comment]
Can this issue be closed now?
Also, I'd like to help beautify the website further and add more examples.
Let me know if there is scope for that?

**Comment by lovasoa** [comment]
Hi ! Yes, your help would be welcome, feel free to open a pull request !

I'm closing this issue
