### ISSUE TITLE
Is this supported for web mobile app such as Cordova?

### ISSUE THREAD

**Issue by Txiaozhe** [sql-js/sql.js#365]
I have a web mobile app by cordova, I use mobile-nodejs and sql.js in it. But it can not run because of the error of webassembly.
Could you please give me some help.

**Comment by lovasoa** [comment]
Hello, 
  We do not provide specific support, but if you have a bug report, you can do it here.
  sql.js distributes both a wasm and a simple javascript version, so it should work on most platforms where javascript runs.
