### ISSUE TITLE
branding - github-org logo

### ISSUE THREAD

**Issue by kaizhu256** [sql-js/sql.js#368]
not a designer, but i played around with 2 basic logo variants on jsfiddle @ https://jsfiddle.net/kaizhu256/2yspma6f/

styled after ecmascript and js.org's logos.  uses free google-font.  what do you think?

![image](https://user-images.githubusercontent.com/280571/76290045-7498f400-6278-11ea-82a3-7aba6981d9c7.png)

**Comment by lovasoa** [comment]
this looks good to me

**Comment by kaizhu256** [comment]
![sql js logo 200x200](https://user-images.githubusercontent.com/280571/76377464-f8a2b880-6318-11ea-8334-763732b1401b.png)

decided to go with first variant.  if it looks ok, can you update org-portrait with above 200x200 logo?

**Comment by kaizhu256** [comment]
![sql js logo 400x400 smushed](https://user-images.githubusercontent.com/280571/76381653-fb56db00-6323-11ea-97b9-8c9a220fe9d3.png)

higher-res 400x400 png.  updated js-fiddle @ https://jsfiddle.net/kaizhu256/2yspma6f/14

**Comment by lovasoa** [comment]
I checked in a vector version of the logo on git, so that people can contribute to it via pull requests.

**Comment by lovasoa** [comment]
![sqljs](https://user-images.githubusercontent.com/552629/76405509-87025300-6388-11ea-86c9-af882abb00bd.png)
