### ISSUE TITLE
transfer repo `kaizhu256/sql.js-dist` -> `sql-js/sql.js-dist`

### ISSUE THREAD

**Issue by kaizhu256** [sql-js/sql.js#369]
created dist-repository https://github.com/kaizhu256/sql.js-dist containing dist-files for all released versions.  its modeled after https://github.com/tinymce/tinymce-dist .

reason is because people like me might want to create "debug" demos on jsfiddle and not be bothered with having to host specific dist-versions of sql.js somewhere on the web:

```html
<!DOCTYPE html>
...
<script src="https://github.com/kaizhu256/sql.js-dist/raw/v1.1.0-dist/dist/sql-wasm-debug.js"></script>
<script>...</script>
```

if its ok with org-owners, i will transfer the repo over.

note: there will be an extra chore when doing releases -- either release-committer or org-member (i can volunteer) need to manually merge released source-code and dist/ files into the repo

![image](https://user-images.githubusercontent.com/280571/76688785-3562fe00-65fe-11ea-840d-5b0e7a040925.png)

**Comment by lovasoa** [comment]
I don't think this is necessary. sql.js is already distributed on CDNs for these usecases

**Comment by lovasoa** [comment]
See: https://cdnjs.com/libraries/sql.js

But I appreciate the initiative :+1:

**Comment by lovasoa** [comment]
We may want to better advertise the CDNs, though. Globally, I think the README could be improved a lot.
