### ISSUE TITLE
maybe sql-wasm is not faster than sql-wasm-debug?

### ISSUE THREAD

**Issue by kaizhu256** [sql-js/sql.js#371]
have internal webapp that originally used the `sql-wasm-debug.wasm` to ingest and manipulate 50mb csv.

recently i evaluated its performance in `sql-wasm.wasm`, and see no performance improvement:

moderate-complexity joins and mappings on ~200k row tables:
1. sql-wasm:
    - task1 - 36 seconds to complete
    - task2 - 92 seconds to complete

2. sql-wasm-debug:
    - task1 - 37 seconds to complete
    - task2 - 85 seconds to complete (actually faster, but probably within margin of error)

obviously more data is needed for conclusive result, but if it turns out theres no real performance gain in most applications, perhaps we could recommend debug-build for everything (and reduce confusion with all the dist-file variants)?

![image](https://user-images.githubusercontent.com/280571/76778371-b85b9400-6777-11ea-9fa0-92a7f3d88ed7.png)

**Comment by brodybits** [comment]
Interesting. What about download size?

**Comment by kaizhu256** [comment]
```
sql-wasm binary:       1157661 bytes
sql-wasm-debug binary: 1709733 bytes (48% bigger)
```

**Comment by lovasoa** [comment]
The largest performance penalty is in the download and initialization time. sql-wasm.js is several times smaller than the debug js file.

**Comment by kaizhu256** [comment]
sorry, the size difference was due to different versions v1.1.0 vs v1.2.1.

if i compare using latest v1.2.1, the file-size is smaller:

```
comparing sql-wasm vs sql-wasm-debug using same version v1.2.1

file size:
sql-wasm.wasm       - 1157661 bytes
sql-wasm-debug.wasm - 1190796 bytes (3% bigger)

time to complete task1:
sql-wasm            - 36 seconds
sql-wasm-debug      - 35 seconds (3% faster)

time to complete task2:
sql-wasm            - 83 seconds
sql-wasm-debug      - 85 seconds (2% slower)
```

![image](https://user-images.githubusercontent.com/280571/76784065-fe692580-6780-11ea-9f48-9c826bca020c.png)

**Comment by kaizhu256** [comment]
> sql-wasm.js is several times smaller than the debug js file.

that is true.  i was able to shrink it by 2/3 with terser, but its still twice as big.  but perhaps we could use closure to produce a .min.js version?

```bash
#!/bin/sh
curl -O https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.2.1/dist/sql-wasm.js
curl -O https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.2.1/dist/sql-wasm-debug.js
npm install terser
npx terser sql-wasm-debug.js -c -m --mangle-props > sql-wasm-debug.min.js
ls -l sql-wasm.js sql-wasm-debug.js sql-wasm-debug.min.js

#  52853 bytes sql-wasm.js
# 293457 bytes sql-wasm-debug.js
# 106941 bytes sql-wasm-debug.min.js (102% bigger after minification by terser)
```

**Comment by lovasoa** [comment]
what? We already have a minified version!
