### ISSUE TITLE
Loading 'sql-wasm.js' in a web page, as per the instructions, throws CORS error

### ISSUE THREAD

**Issue by accron-1** [sql-js/sql.js#373]
Following the instructions in the Readme, section [Inside the browser](https://github.com/sql-js/sql.js#inside-the-browser) for how to reference the sql.js file, does not work:

`<script src='/dist/sql-wasm.js'></script>`

The following error occurs on page load:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at file:///home/user/projects/sql.js/js/sql-wasm.wasm. (Reason: CORS request not http).`

`TypeError: NetworkError when attempting to fetch resource.sql-wasm.js:166:129`

However, everything works if I instead reference `sql-asm.js`, but according to the docs `asm` is slower and older tech, and should not be used.

System:
Linux Manjaro, Firefox 74.0

**Comment by lovasoa** [comment]
Hello and thank you for getting in touch !
  The code in the example does work, but you cannot use it with local files (with the `file:` protocol).
  You can still test it by starting a local web server.
  You can read this explanation page on the mozilla dev network for more information: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server
  In short, you can start a local web server with php using `php -S localhost:8000` or with python using `python3 -m http.server`.

**Comment by accron-1** [comment]
Firstly, thank you for an awesome library!

It could be a good idea to update the docs with that info.

Either way, the sql-asm.js does work with `file:`, so it's fine for the tests I want to do. But it's good to know the `wasm` version will work in a live env.

**Comment by MvGulik** [comment]
>It could be a good idea to update the docs with that info.

A super lazy options could have been to just add a link "there" to this issue.
Which might be less than one minute work for one person.
But could potentially save countless minutes for countless others. (_potential also something else_ ...)
Sounds like good economics to me. Although probably a bit to social in nature (_considering the current world affairs_).

But than again ...
>this is not a support forum.

Got it ...
