### ISSUE TITLE
discussion - javascript styleguide-incompatibilities between /src/, /test/, /examples/

### ISSUE THREAD

**Issue by kaizhu256** [sql-js/sql.js#382]
intend to begin work linting directories /test/ (and possible /examples/).  need to address:

#### use `var` or `let/const`?
- i have no preference
- i guess eslint prefers let/const, since it requires rule-relaxation to allow var
- if stay with `var`, should add eslint-rule `"block-scoped-var": "on"`,
    to guard against current code like `for (var i = 0; i < argc; i += 1)`
    (`var i` is actually scoped outside the for-loop)
- if go with `let/const`, should remove the var eslint-rules:
    - `"no-var": "off"`
    - `"vars-on-top": "off"`

#### 2-space indent or 4-space indent?
- i prefer 4-space
- 4-space is eslint-default - https://eslint.org/docs/rules/indent
- 2-space is airbnb-default - https://github.com/airbnb/javascript#whitespace

#### use async/await or Promise(...).then(...)?
- i prefer async/await and reverting to Promise.then for files like src/api.js, if it turns out emcc/closure cannot handle es8.

#### limit column-width to 80, 100, 120, 160?
- i prefer 80 (`"max-len": { code: 80 }`)
- 80 is eslint-default - https://eslint.org/docs/rules/max-len

these are some of the styleguide-incompatibilities i see though i'm sure there's more

**Comment by lovasoa** [comment]
I'd like to avoid unmotivated style changes to api.js, but that's all. It may be nice to have a single code style for the api and the tests, but I don't have any strong opinion on this, you can do as you see fit @kaizhu256.

**Comment by kaizhu256** [comment]
k, would tightening rule to 80-column limit `"max-len": { code: 80 }` be acceptably motivated?

**Comment by lovasoa** [comment]
yes, it's ok
