### ISSUE TITLE
Why sql.js?

### ISSUE THREAD

**Issue by guettli** [sql-js/sql.js#386]
I hope you don't feel offended by this question.

Why do you think sql.js is useful?

If I were you, I would answer the "why?" question in the README.

**Comment by lovasoa** [comment]
Hello,
  No offense taken 😄 . sql.js is currently the only way to run SQL queries against a standard relational database on the client side on the web. There are many different use cases for this. If you want some examples, you can give a glance at the list of the [1875 github repositories that depend on sql.js](https://github.com/sql-js/sql.js/network/dependents?package_id=UGFja2FnZS0xMzgwNDgwOQ%3D%3D). If you then want to make a small summary of the various use cases under the form of a *Why sql.js* section in the README, you can open a pull request and we'll merge it.

**Comment by guettli** [comment]
created: https://github.com/sql-js/sql.js/pull/387
