### ISSUE TITLE
sql.js use memory or disk?

### ISSUE THREAD

**Issue by hoogw** [sql-js/sql.js#391]
I use sql.js browswer distribution, use it in browser.

When I create a table or virual table, 

Where sql.js store the database file? in Memory? or on Disk?

**Comment by lovasoa** [comment]
Hello,
  As explicitly stated in the [README](https://github.com/sql-js/sql.js#sqlite-compiled-to-javascript-), sql.js stores databases in memory:
> It uses a virtual database file stored in memory, and thus **doesn't persist the changes** made to the database.

**Comment by hoogw** [comment]
I have compare sql.js with lunr.js in terms of full text search.

Both use in memory storage,

small to medium size data, both are same fast,

but when large data, 150k json items will crash lunr.js, run out of memory, not sure why.
however, same dataset, 150k json items insert as 150k row into sqlite table, no crash, full text search still same fast, no delay.

sqlite wins here.

**Comment by brodybits** [comment]
> As explicitly stated in the [README](https://github.com/sql-js/sql.js#sqlite-compiled-to-javascript-), sql.js stores databases in memory:
> [...]

It is also documented how to read and write database to disk on Node.js, how to use with user-chosen file on browser, and how to use with file from the server. I have never tried these scenarios and cannot say how efficient they would be, but thought it would be worth mentioning that these scenarios *should* be possible.

**Comment by lovasoa** [comment]
Yes, maybe we want to make it more explicit that even though databases in sql.js are always fully in-memory, it is of course possible to load files from disk to memory and dump databases from memory to files on disk.

**Comment by abdes-zakari** [comment]
> Yes, we may want to make it more explicit that even though databases in sql.js are always fully in-memory, it is of course possible to load files from disk to memory and dump databases from memory to files on disk.

How i can save data in disk instead of memory ? ( I'm testing Sql.js in the browser)

**Comment by abdes-zakari** [comment]
Why storing data in the memory? what's the benefit ? and what kind of data can be stored in the memory?

**Comment by abdes-zakari** [comment]
@lovasoa  Why storing data in the memory? what's the benefit ? and what kind of data can be stored in the memory?
