### ISSUE TITLE
wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.

### ISSUE THREAD

**Issue by hoogw** [sql-js/sql.js#393]
I run into error:

            `wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.

            falling back to ArrayBuffer instantiation

`

here is my code

                       ` config = {
                                                              locateFile: (filename, prefix) => {
                                                                console.log(`prefix is : ${prefix}`);
                                                                return `/public/utility/sqljs/${filename}`;
                                                              }
                                                            }

                                                            // The `initSqlJs` function is globally provided by all of the main dist files if loaded in the browser.
                                                            // We must specify this locateFile function if we are loading a wasm file from anywhere other than the current html page's folder.
                                                            initSqlJs(config).then(function(SQL){`

**Comment by kaizhu256** [comment]
this is not a javascript problem.  the problem is your web-server, which needs to give a response-header `Content-Type: application/wasm` when serving the `sql-wasm.wasm` file:

![image](https://user-images.githubusercontent.com/280571/81721456-7f713000-9445-11ea-9e77-e8014054ad5e.png)

**Comment by hoogw** [comment]
agree,  I use node.js express as server, to serve this file

type is NOT right, 
how to fix it on node.js server?
![image](https://user-images.githubusercontent.com/419582/81722328-11713c80-9436-11ea-89bb-8c5742060acf.png)

**Comment by hoogw** [comment]
why loading 2 copy of  wasm file?

This is the second file
![image](https://user-images.githubusercontent.com/419582/81722591-72991000-9436-11ea-90d9-7406a3cacd56.png)

**Comment by kaizhu256** [comment]
i wouldn't know how to configure your express server, unless i saw the code.

anyways, here's a simple http-server in nodejs that will correctly serve `.wasm` files with proper response-header:

```js
/*
 * fileserver.js
 * usage: PORT=8080 node fileserver.js
 */
"use strict";
let processCwd;
processCwd = process.cwd() + (
    process.platform === "win32"
    ? "\\"
    : "/"
);
process.env.PORT = process.env.PORT || "8080";
console.error("http-file-server listening on port " + process.env.PORT);
require("http").createServer(function (req, res) {
    let file;
    file = require("path").resolve(
        processCwd,
        require("url").parse(req.url).pathname.slice(1)
    );
    // security - disable parent-directory lookup
    if (file.indexOf(processCwd) !== 0) {
        res.statusCode = 404;
        res.end();
        return;
    }
    require("fs").readFile(file, function (err, data) {
        if (err) {
            res.statusCode = 404;
            res.end();
            return;
        }
        switch (require("path").extname(file)) {
        // properly handle .wasm mimetype
        case ".wasm":
            res.setHeader("content-type", "application/wasm");
            break;
        }
        res.end(data);
    });
}).listen(process.env.PORT);
```

**Comment by hoogw** [comment]
I fixed my problem by: use CDN file
no more error


                    `config = {
                                                            //locateFile: filename => `/dist/${filename}`
                                                            locateFile: file => `https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.2.2/dist/${file}`

                                                                                 // cdn :   https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.2.2/dist/sql-wasm.js
                                                           }`

**Comment by hoogw** [comment]
Finally found the ultimate solution:

   enable express.js recognize .wasm file by, 

   update type-is version to 1.6.16 + 
   because 1.6.16 add support .wasm file
 
![image](https://user-images.githubusercontent.com/419582/82085227-81372f80-96a1-11ea-96e4-63ee6870b733.png)


I use 1.6.15,  not support .wasm file, so express will by default set response header to application/octet-stream

![image](https://user-images.githubusercontent.com/419582/82085096-5056fa80-96a1-11ea-8a93-537d5e10e680.png)

**Comment by hoogw** [comment]
first update express.js from 4.15 to 4.17 by modify package.json file, 
change 4.15 to 4.17 as picture show
then run 

                  npm install express

<img width="816" alt="image" src="https://user-images.githubusercontent.com/419582/82088794-40421980-96a7-11ea-9849-5578c943ccbc.png">

app.js file add log, output current running express version
just make sure it is 4.17
<img width="690" alt="image" src="https://user-images.githubusercontent.com/419582/82089927-68cb1300-96a9-11ea-882d-f0a1fcc86da9.png">




Now install type-is, run 

                  npm install type-is
Make sure package.json type-is version is 1.6.18
<img width="919" alt="image" src="https://user-images.githubusercontent.com/419582/82089260-26ed9d00-96a8-11ea-81f4-35aba41e66e9.png">

Now my express.js support .wasm file by response correct header content-type application/wasm
