### ISSUE TITLE
How to NOT block DOM UI?  async?

### ISSUE THREAD

**Issue by hoogw** [sql-js/sql.js#394]
I have very large static json data (150k count)

When I initially create table, insert 150k , it block the browser UI, not responsive, until insert completed

Ideally I am ok with long time it took for inserting,  indexing, as long as it NOT block UI.

I know if I move operation into  web worker, it will not block main thread UI.
But it complex other thing, not wanted.

sql.js seem asynchronous already,see below code.
but why, for large data, it still block DOM UI?????

      `
         
          initSqlJs(config).then(function(SQL){

              // async code here, should not block DOM UI, 
             // however, it did BLOCK UI, browser not responsive until insert finished.

                db.insert...

       }

`

**Comment by brodybits** [comment]
My understanding is that only the `initSqlJs` function should be considered asynchronous. The other operations would be using synchronous code.

For a case like yours, I would recommend that you consider starting a transaction with BEGIN, inserting the data in chunks, and finishing with COMMIT once all data is inserted. This would insert the data in an atomic manner.

**Comment by lovasoa** [comment]
Hello, 
  As you mentioned, the only way to interact asynchronously with your database is to use a web worker. As brodybits mentions, you can also make several smaller blocking transactions, which will be slower, but won't block the UI thread.

**Comment by hoogw** [comment]
@brodybits @lovasoa 
Perfect, I am new to here, can you show some hint, how to  smaller blocking transactions by begin, chunk, and commit, atomic manner?

**Comment by lovasoa** [comment]
You can read this page of the sqlite documentation about transactions: https://www.sqlite.org/lang_transaction.html

Inside the transaction, just insert your data chunk by chunk, using the normal sql.js API

**Comment by hoogw** [comment]
here is my performance results:

by add begin transaction , commit,  
use 12.4 seconds
![image](https://user-images.githubusercontent.com/419582/81949358-a0f22900-95b7-11ea-84b4-8509a49aa17c.png)

![image](https://user-images.githubusercontent.com/419582/81949466-bebf8e00-95b7-11ea-9d63-9379c91e68a9.png)

**Comment by hoogw** [comment]
without transaction, commit, 
use 50 seconds, cause DOM ui block for 50 seconds
![image](https://user-images.githubusercontent.com/419582/81950104-650b9380-95b8-11ea-8881-e8d921086b8d.png)

![image](https://user-images.githubusercontent.com/419582/81950200-810f3500-95b8-11ea-8199-2556016c44f9.png)

**Comment by hoogw** [comment]
Conclusion:
   
      test 150k insertion, 

       by add begin transaction , commit,
       use 12.4 seconds, cause DOM ui block for 12.4 seconds ( recommended ) 

       without transaction, commit,
       use 50 seconds, cause DOM ui block for 50 seconds ( not acceptable )


always use transaction, always, 
 
My further question is: 

Even use transaction, I thought it should be 0 block, but it still cause 12 sec UI block time
The reason, I guess, maybe, is not sqlite iteself, it is because when I build sql insert statement, I need to processing the string,  see below for loop(150k loop), the biggest cost is below 2 line, 300ms 



               _raw_value = String(_elem_feature.properties[_properties_array[p]]);     // must String() for next step use replace()
                _insert_value = _raw_value.replace(/'/g, ' ');     


 
(300ms+300ms) * 150k should equal 50 sec total, but it is not 

I did't know why, I don't know how this tool chrome console/performance tool calculate the for loop time.


for both of you,@lovasoa @brodybits   do you know why, 
it should be 0 block time with transaction commit. However it is still 12 sec?



![image](https://user-images.githubusercontent.com/419582/81951266-cc761300-95b9-11ea-8a49-5f2df1d157c7.png)

**Comment by brodybits** [comment]
We see the good news that using transactions can speed things up, bad news is that the commit can take some time in case of a large transaction. I think the underlying synchronous processing and I/O design of SQLite is self-evident. And SQLite seems to have many (many) thousands of lines of C code, which would translate into obviously non-zero processing time for this kind of transaction. (Asm.js & WASM not always as efficient as compiling C into CPU-specific object code.)

I am now thinking of the following alternatives for avoiding UI blocking:

- consider SQL.js in a worker, as suggested & discussed before
- insert the data in smaller transactions

The drawback of inserting the data in smaller transactions is the possibility of inconsistent state during startup. This may or may not turn out to be a real issue now or at some point in the future.

**Comment by lovasoa** [comment]
@hoogw It looks like you are manually forming an SQL query by concatenating strings. You should probably use prepared statements for what you are doing instead. This would be faster, more secure, and less bug-prone.

**Comment by hoogw** [comment]
@brodybits 

I am going this direction, soon will get results.  It should be NO MORE  DOM block

> * consider SQL.js in a worker, as suggested & discussed before

**Comment by hoogw** [comment]
> @hoogw It looks like you are manually forming an SQL query by concatenating strings. You should probably use prepared statements for what you are doing instead. This would be faster, more secure, and less bug-prone.

@lovasoa  Got it. good idea, working on it. 

Now I try to move everything to webworker, using worker.sql-wasm.js
by a way, what asm is for (worker.sql-asm.js)

<img width="263" alt="image" src="https://user-images.githubusercontent.com/419582/81975962-ab72e980-95dc-11ea-8dce-e2f26c85c6f6.png">

**Comment by hoogw** [comment]
I run into error with web worker 


![image](https://user-images.githubusercontent.com/419582/81977843-816ef680-95df-11ea-8e2b-e5fc5a507746.png)

I download from release 1.2.2
![image](https://user-images.githubusercontent.com/419582/81977986-aebba480-95df-11ea-8402-4f171daae7e9.png)

This is my web worker code:
     
<img width="470" alt="image" src="https://user-images.githubusercontent.com/419582/81978075-d6127180-95df-11ea-8213-5f4a358d3016.png">

sql-wasm.wasm was shared by both worker version and non-worker version, right?

this is my lib file, have only 3 file, for both worker version and non-worker version
![image](https://user-images.githubusercontent.com/419582/81978326-386b7200-95e0-11ea-9286-0123569af540.png)

**Comment by brodybits** [comment]
A couple more ideas maybe US$0.02 worth:

- What if you would try prepared statements without using a web worker?
- Can you make an isolated test or demo program to try out your database capabilities?

The little I see from your screenshots looks like a nice app, wouldn't mind a link if it is publicly usable.

**Comment by hoogw** [comment]
> A couple more ideas maybe US$0.02 worth:
> 
> * What if you would try prepared statements without using a web worker?
> * Can you make an isolated test or demo program to try out your database capabilities?
> 
> The little I see from your screenshots looks like a nice app, wouldn't mind a link if it is publicly usable.

Yes, but I have not make sqlite working.
Here is current non-sqlite version.

you can try click any city, then click google map icon, to bring up maps

          [https://transparentgov.net/cleargov1/418/arcgis-server-1000-org](https://transparentgov.net/cleargov1/418/arcgis-server-1000-org)

**Comment by kaizhu256** [comment]
the error `expected magic word ...` means the file `sql-wasm.wasm` is corrupt or has a version mismatch with `worker.sql-wasm.js`.

make sure `worker.sql-wasm.js` and `sql-wasm.wasm` are from the same version-package/cdn-source.

**Comment by hoogw** [comment]
> the error `expected magic word ...` means the file `sql-wasm.wasm` is corrupt or has a version mismatch with `worker.sql-wasm.js`.
> 
> make sure `worker.sql-wasm.js` and `sql-wasm.wasm` are from the same version-package/cdn-source.
@kaizhu256 
let me try it, good suggestion

@brodybits 
this is 150k point map, 
[https://transparentgov.net:3200/googlemaps2/default?layer=BOE+Permits+Points&url=https%3A%2F%2Fgeohub.lacity.org%2Fdatasets%2Fee97d9bb52574615b41bf5a0cf08cfb5_1.geojson%3FoutSR%3D%7B"latestWkid"%3A3857%2C"wkid"%3A102100%7D&center_zoom=10&center_lat=34.06850078782453&center_long=-118.0657711441673
](150k point map, with lunr.js try to convert to sqlite, since lunr failed on full text search)

**Comment by hoogw** [comment]
I guess, web worker path some how cause the problem. I make sure use same version, always, all 1.2.2, also I seperate work version into 'worker' folder avoid polute.

The error cause by 'importscript' wasm, you can see below, import itself, success, load worker-sql-wasm.js file(success here), but further processing this file initiator another 3 http request see below right side, those 3 path isn't correct,(see red color error left side) 

![image](https://user-images.githubusercontent.com/419582/82067793-07de1380-9686-11ea-81dc-78507b2c7724.png)
 
this is my config file( not sure is correct?)
<img width="1377" alt="image" src="https://user-images.githubusercontent.com/419582/82068342-b1bda000-9686-11ea-8231-38dd1a6b6b8e.png">

this is importscript, see I isolate worker version into sqljs/worker/...  worker folder
<img width="705" alt="image" src="https://user-images.githubusercontent.com/419582/82068496-e9c4e300-9686-11ea-9553-b1cc811465f6.png">
![image](https://user-images.githubusercontent.com/419582/82068593-0a8d3880-9687-11ea-92ba-90277abc2ae3.png)

seems like my config file isn't correct? it is wrong path

               (wrong path)   http://localhost:3000/public/javascripts/webworker/sql-wasm.wasm

                (should be )   http://localhost:3000/public/javascripts/utility/sqljs/worker/sql-wasm.wasm

                  seems like it auto enforce use  '/webworker/' as path

                  but my path is   'utility/sqljs/worker'

                  how to config customized path in config file?

![image](https://user-images.githubusercontent.com/419582/82068957-8a1b0780-9687-11ea-9cce-774d5fba4bea.png)

![image](https://user-images.githubusercontent.com/419582/82068760-488a5c80-9687-11ea-8b8f-88c0aeaf8e27.png)

**Comment by hoogw** [comment]
#366 mentioned webworker shipped is out of box version, that is why it enforce use path      

                        .../webworker/sql-wasm.wasm

I need to customized path to my folder

                           .../utility/sqljs/worker/sql-wasm.wasm

Without customize path, wrong path cause error see above screenshot

**Comment by kaizhu256** [comment]
search your entire code-base for string `javascripts/webworker` and change it to correct path.  if your project is under git-version-control, you can run following shell-command:

```bash
git grep 'javascripts.webworker'
```

**Comment by hoogw** [comment]
@kaizhu256   you probably means search in sql-js project right?
I do not setup source code for sql-js, I only copy those dist files

search my own project is here, nothing related to sql-js

<img width="698" alt="image" src="https://user-images.githubusercontent.com/419582/82074250-5643e000-968f-11ea-8aa1-edb3a15c2dbd.png">

I kind of fix the error by copy/past wasm file to the wrong path folder, fix that. 

So when importScript() load, it will use wrong path location wasm file.
when config() runs, it will use correct path location wasm file. 

I have 2 same wasm file in 2 location, server above to operation, temp fix the error, so I can move on.

I run into further issue:

do we have the web worker version of this 

                     locateFile: file => `https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.2.2/dist/${file}`

above is one I use for non-web-worker version fix the applicaton/wasm type error, since my node.js server do not response wasm type, I use above code fix it. full code see below.

<img width="888" alt="image" src="https://user-images.githubusercontent.com/419582/82075768-a1f78900-9691-11ea-8a11-c6037b561472.png">


Do we have a web worker version of above file on cloudflare.com?

**Comment by hoogw** [comment]
web worker version have bugs???

this web worker version, 

create table success, 
insert row success, 

but when search, no error output, but result is always empty, not matter what sql use.
if I feed a wrong sql, it will complain sql statement is wrong. 
if I feed a valid sql, it always return nothing, not even any error, just empty 


![image](https://user-images.githubusercontent.com/419582/82081527-55b14680-969b-11ea-9a6f-895b0d300011.png)

Where I can prove that web worker version 1.2.2 is working?
My copy only works for 'insert', but not 'select'

**Comment by hoogw** [comment]
#393 I just find the ultimate solution to fix the .wasm type issue, 
now express.js server use type-is.js to support .wasm file type, by response header content-type correctly with application/wasm, no more error, no need to use CDN .wasm file.(I previousely used for temp fix)

but still get empty when 'select'
I rule out the .wasm issue, 

isolate the issue is inside,     worker.sql-wasm.js file

                      // web worker only
                      importScripts('../../utility/sqljs/worker/worker.sql-wasm.js')

It could be some bug inside worker.sql-wasm.js, that when select, always 0 output.
but insert is fine.

**Comment by brodybits** [comment]
> now express.js server use type-is.js to support .wasm file type
> [...]

I think it would be nice to get this documented, may help some other users in the future.

**Comment by hoogw** [comment]
Never mind, it is my code error, sql-js web worker version working fine.
Now I have get everything all working, fixed all issue. 

@brodybits yes,  I spends  5 hours, dig, dig and dig, finally find the solution.
This will save other people 5 hours trouble when they use sql-js, when they load .wasm file.

To support .wasm file, latest
 express v4.17 and type-is v1.6.18 is needed.

I had express v4.15 and type-is v1.6.15, which will NOT support .wasm file, 
console keep warning:  content type is not match.
