### ISSUE TITLE
Broken and incorrect link on "examples" page

### ISSUE THREAD

**Issue by abetusk** [sql-js/sql.js#396]
The [Examples](https://sql-js.github.io/sql.js/index.html) page has a broken link at the bottom in the text "...  examples locally, see ./examples/readme.md". It should be (presumably?) [here](https://github.com/sql-js/sql.js/blob/master/examples/README.md).

The "source on Github" link at the bottom points to the old "kripken" repo and not to the most current (should be [this link](https://github.com/sql-js/sql.js).

**Comment by lovasoa** [comment]
Link fixed in 7b2f928ead46b4b9af7fcea6d4703f628b69f9ed

Thank you for reporting this !
