### ISSUE TITLE
wasm worker error: modules doesn't start with '\0asm'

### ISSUE THREAD

**Issue by yifanwu** [sql-js/sql.js#402]
Hi there, with the current version, I keep on running into the following error with the example GUI code `Error: WebAssembly.Module doesn't parse at byte 0: modules doesn't start with '\0asm'`

I even tried to download all the files from https://sql-js.github.io/sql.js/examples/GUI/index.html (since it's working for me), but still getting the same error.

I'm not sure how to debug since all the set up as far as I'm concerned is the same, but the result is different? I'm starting to suspect that it's because I was either using Python simple server or webpack in both of my attempts to use the wasm worker... However I tried https://gist.github.com/prideout/09af26cef84eef3e06a1e3f20a499a48 and it still doesn't seem to make a difference. Please let me know if you know of a config that works! Thanks.

Help much appreciated!!!

**Comment by yifanwu** [comment]
I somehow fixed this by using `path.resolve` on the worker wasm js file. I could close the issue, but I would like to know why that made a difference (I don't think the file path was incorrect since the error was within the worker file and not accessing the worker file). Thanks!

**Comment by lovasoa** [comment]
You were probably not referencing a path to a valid wasm file in locateFile.
