### ISSUE TITLE
sql.js pre-compressed with Brotli:11 on open source CDN

### ISSUE THREAD

**Issue by praisedpk** [sql-js/sql.js#405]
I have added sql.js on PageCDN. Current size of [sql-wasm.wasm](https://pagecdn.io/lib/sqljs/1.3.0/dist/sql-wasm.wasm) on PageCDN is just **324 KB** that is around 66 KB smaller than normal due to better compression. The files are available on CDN here: https://pagecdn.com/lib/sqljs

Adding this CDN link on download page is helpful for users looking to reduce JS size.

Thanks.

**Comment by lovasoa** [comment]
Hello,
  We already have a link to cdnjs, which also uses brotli compression.

**Comment by praisedpk** [comment]
Hi @lovasoa 

Yes, but the size difference is **66 KB** even if both CDNs use Brotli (the CDNJS version is 20% bigger). Here is a comparison:

    PageCDN          324 KB
    CDNJS            389 KB
    Difference        66 KB appx.

The decision is yours, but I believe developers will love to have smaller files of SQL.js.

Thanks.

**Comment by lovasoa** [comment]
You should report that to cdnjs, then
