### ISSUE TITLE
Error: File is not a database

### ISSUE THREAD

**Issue by pringithub** [sql-js/sql.js#411]
Hi,

I'm trying to load a sqlite3 database I created in python, but am getting the error saying that the file is a database .. I can load it using `sqlite3 test.db` just fine

```
  config = {
      locateFile: filename => `https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.3.0/dist/${filename}`
  }

  initSqlJs(config).then(function(SQL){
    //Create the database
    var db = new SQL.Database('../../db/test.db');
    console.log(db)

    var res = db.exec("SELECT * FROM projects")
    console.log(res)
  });
```

```
sql-wasm.js:87 Uncaught (in promise) Error: file is not a database
    at b.handleError (sql-wasm.js:87)
    at b.exec (sql-wasm.js:84)
    at cute.html:44
```

**Comment by lovasoa** [comment]
As written in the README and the documentation, the constructor of `SQL.Database` does not expect a string containing a path to a database, but the bytes of the database file itself.

See https://github.com/sql-js/sql.js#loading-a-database-from-a-server
