### ISSUE TITLE
discussion - feasibility to integrate `https://wicg.github.io/file-system-access/`

### ISSUE THREAD

**Issue by kaizhu256** [sql-js/sql.js#422]
one of sql.js biggest limitation is inability to persist largish databases (e.g. 1gb) to local filesystem.

that might finally be overcome with newly proposed https://wicg.github.io/file-system-access (note spec's motivation appears mainly saving data in web-editors and ides).
they have an [experimental demo here](https://googlechromelabs.github.io/text-editor/)

feasibility question - what additional spec read/write features are needed to allow sql.js to use spec to persist to local filesystem?

spec's current capabilities are (from what i gather):
#### read
- await FileSystemHandle.file() // method returns blob/file object

#### write
- await FileSystemWritableFileStream.write(data)
- await FileSystemWritableFileStream.write({ type: "write", data: data })
- await FileSystemWritableFileStream.write({ type: "write", position: position, data: data })
- await FileSystemWritableFileStream.write({ type: "seek", position: position })
- await FileSystemWritableFileStream.write({ type: "truncate", size: size })

**Comment by lovasoa** [comment]
This is an interesting spec. However this is probably something that will be integrated at the emscripten level, and not at the level of individual libraries.

**Comment by kaizhu256** [comment]
k, moving this issue to https://github.com/emscripten-core/emscripten/issues/12428
