### ISSUE TITLE
Support for SpatialLite?

### ISSUE THREAD

**Issue by amaurymartiny** [sql-js/sql.js#424]
Is it possible to use SpatialLite with sql.js? https://www.gaia-gis.it/fossil/libspatialite/index

I am looking for an alternative DBMS to postgres + postgis.

**Comment by lovasoa** [comment]
Hi !
  Yes, it's possible, but you'll have to recompile sql.js yourself. See https://github.com/sql-js/sql.js/issues/392
  If you need help doing that, don't hesitate to ask.

P.S. Passe le bonjour à Clara :wink:

**Comment by lovasoa** [comment]
And if all you need is a spatial index, the easiest solution is to use the [RTree module](https://sqlite.org/rtree.html) of SQLite, by simply adding `-DSQLITE_ENABLE_RTREE=1` in the Makefile.
