### ISSUE TITLE
Why do you suggest to use sqllite3 native with Electron  ? 

### ISSUE THREAD

**Issue by Barbarosse** [sql-js/sql.js#425]
Hi, I have a confusion : I read that Sql.js have better performance and easy to implement in code ; in my case I have sqlite databases files that I only need to select from without any modifications, if I use native sqlite I have to send data between the main process and the renderer back and forth. 
Can you explain why you have suggested native instead of sqljs in Electron  ? 
Thanks

**Comment by lovasoa** [comment]
I am closing this because it's not an issue, but let's discuss that below.

**Comment by Barbarosse** [comment]
Ok. Can you clarify it for me ?

**Comment by lovasoa** [comment]
I am no electron expert, but unless I'm mistaken, you can require a native nodejs module from a renderer process, so you shouldn't have to send data back and forth between processes.
