### ISSUE TITLE
Ignored pull request

### ISSUE THREAD

**Issue by cpainterwakefield** [sql-js/sql.js#427]
Hi maintainers: can I please get an answer on my proposed pull request ( #413 )?  I submitted it a month and a half ago, and I haven't heard anything.  I have a project that is completely stalled because I need the functionality I implemented in the PR; I just need to know: will you incorporate my PR (I can make changes if desired), or not?  If not, I will fork and get back on track with my project, but I'd prefer to keep using sql.js!

Thank you.

**Comment by lovasoa** [comment]
Hi @cpainterwakefield ! 
  I'm sorry for not answering earlier, and thanks for the heads up. I'll try to merge this today.

**Comment by cpainterwakefield** [comment]
Oh, thank you!

**Comment by lovasoa** [comment]
I added my comments on the PR :slightly_smiling_face:

**Comment by cpainterwakefield** [comment]
Thanks - I will go through these and respond.

**Comment by lovasoa** [comment]
The main question is around the ideal API. I feel like a single function that does everything is not what the library should be doing.

**Comment by lovasoa** [comment]
Also, if you could describe your usecase, it would help shape a good api.

**Comment by cpainterwakefield** [comment]
Right, I started out to build it as a more modular thing, but I recall that I got into some issues with it that made me go the direction of one monolithic function.  Let me look back at the code to see if I can remember where I ran into problems.

My use case is very different, I would guess, than most.  I'm working on educational software, where students will be encouraged to play in a sandbox database and try whatever they want.  As part of that, they should be able to execute scripts with multiple SQL queries.  I want to be able to give them very detailed feedback for each query.

I have a kludge that maybe works most of the time to parse a block of SQL into separate queries, but it is tricky to get right (especially with comments!), and there may be constructs that will not work with my kludge.  It seems like the *right* thing to do is to let the sqlite library parse the block.  The current API doesn't give any fine-grained control on that.  I'll look more closely at your iterator suggestion, that sounds very promising.

**Comment by lovasoa** [comment]
It's great to see sql.js used for education. I've seen that before, and I myself started working on this project at the university.
And yes, I do agree 100% that the sql parsing should be done by sqlite and not by the client application. I think we can combine the parsing by sqlite and the flexible execution by the client application.
