### ISSUE TITLE
Integrate sql.js with WebPack/React.js without react-app-rewired

### ISSUE THREAD

**Issue by iwangotamarjo** [sql-js/sql.js#430]
I'm trying to integrate `sql.js` into my WebPack/React.js app but without using react-app-rewired.

Instead, I am trying to configure my WebPack on its own. Added the following line:

```
node: {
    fs: 'empty'
}
```

to base WebPack config after `npm install sql.js webpack-copy-plugin` and added the following line:

```
    new CopyPlugin({ patterns: [{ from: 'node_modules/sql.js/dist/sql-wasm.wasm', to: 'static/js/' }] })
```

to the modules.

However, I am getting the following error still:

![image](https://user-images.githubusercontent.com/73222032/96694595-3db4c000-13bb-11eb-86b7-c22b9152e1c9.png)

How do I get around solving this?

**Comment by lovasoa** [comment]
This should be possible to do even without any plugin, just by using webpack5's [URL assets](https://webpack.js.org/guides/asset-modules/#url-assets) with the file loader : 

something like 

```js
const SQL = await initSqlJs({
  locateFile: file => new URL('./node_modules/sql.js/dist/sql-wasm.wasm', import.meta.url);
});
```

I have never tried it though, so please comment here with your results

**Comment by iwangotamarjo** [comment]
Thanks, let me give it a shot and update over here.

**Comment by lovasoa** [comment]
And to answer your initial question about copyplugin: you should check that sql-wasm.wasm is copied where you want it to be in your assets, and point to it in `locateFile`. You can use your browser's network monitor to debug the issue.

**Comment by lovasoa** [comment]
By looking at the error, it looks like you are trying to load `sql-wasm.wasm` from the root of your server (`/sql-wasm.wasm`), but you instructed copyplugin to put it in `static/js/sql-wasm.wasm`. You should change either the destination of the asset in copyplugin or your `locateFile` directive.

**Comment by iwle** [comment]
Could I also check for using sql.js as a web worker, where can I find `worker.sql-wasm.wasm`? It does not seem to be in the dist/ directory.

**Comment by iwle** [comment]
I am getting the following error, possibly due to an incorrect loader for WASM?

![image](https://user-images.githubusercontent.com/10136421/96698628-ee24c300-13bf-11eb-990f-04cc772a7337.png)

**Comment by iwangotamarjo** [comment]
I am getting the following error, it seems that there is a missing WASM loader in my WebPack. Is that the issue here?

![image](https://user-images.githubusercontent.com/73222032/96698960-4c51a600-13c0-11eb-8215-ce6c29314250.png)

**Comment by iwangotamarjo** [comment]
Could I also check for Web Workers, it doesn't seem like this is working, even though the files (worker.sql-wasm.js and sql-wasm.wasm) are inside my static folder after WebPacking the app.

I could not find the `dist/worker.sql-wasm.wasm` inside the node_modules folder for sql.js.

```
  let worker = new Worker('/static/js/worker.sql-wasm.js');

  worker.onmessage = () => {
    console.log("Database opened");
    worker.onmessage = event => {
      console.log(event.data); // The result of the query
    };
  };
```

**Comment by iwangotamarjo** [comment]
> I am getting the following error, it seems that there is a missing WASM loader in my WebPack. Is that the issue here?
> 
> ![image](https://user-images.githubusercontent.com/73222032/96698960-4c51a600-13c0-11eb-8215-ce6c29314250.png)

Ok I tried using `webassembly-loader` but it failed as well with the same error "You may need an additional loader to handle the result of these loaders."

**Comment by lovasoa** [comment]
No you don't want to use a wasm loader in webpack. All you have to do is configure webpack to copy the wasm files to your assets, and then give the path to the packed asset to locateFile

**Comment by lovasoa** [comment]
the new URL trick is just to allow webpack5 to copy the wasm files to your assets.

**Comment by lovasoa** [comment]
and it is still advised to use sql.js inside a web worker to not block the main thread if you are going to run long queries. But you may prefer to encapsulate your own database logic in your own webworker, over using the basic (but functional) webworker that we distribute.

**Comment by iwangotamarjo** [comment]
Hi @lovasoa, I see thanks! I think I have been doing it the wrong way then. I tried adding the asset rule to WebPack:

```
      {
        test: /\.(wasm)$/,
        type: 'asset'
      },
```

but I have an error on compile:

![Uploading image.png…]()

**Comment by iwangotamarjo** [comment]
Hi @lovasoa, I see thanks! I think I have been doing it the wrong way then. I tried adding the asset rule to WebPack:

```
      {
        test: /\.(wasm)$/,
        type: 'asset'
      },
```

but I have an error on compile:

![image](https://user-images.githubusercontent.com/73222032/96736665-68207080-13ef-11eb-8f8b-421ac058a881.png)

**Comment by lovasoa** [comment]
No. See https://webpack.js.org/blog/2020-10-10-webpack-5-release/

**Comment by iwangotamarjo** [comment]
So I spent the better part of yesterday and today migrating my app to Webpack 5. Unfortunately, it breaks many of my dependencies and I have to stick with Webpack 4. Is there any way to do this in Webpack 4? Or would I have to use react-app-rewired?

**Comment by lovasoa** [comment]
yes, of course you can do that with webpack 4. You just have to make sure the path to which you are saving the wasm file is correctly pointed to in locateFile

**Comment by iwangotamarjo** [comment]
Got it, I have resolved the issue using Webpack 4 and the original `copy-webpack-plugin`. Appreciate the help.

**Comment by kaitian186** [comment]
> yes, of course you can do that with webpack 4. You just have to make sure the path to which you are saving the wasm file is correctly pointed to in locateFile

Hello!
Can you please help me for using the sql.js on my electron and react app.
I am using webpack4 on my app.
Btw, when I call the initSqlJs, I got the following error.
*** property of undefined on sql-wasm.js:92 ***
and, I was blocked by this issue and my app can not progress more.
I think sql.js library is a perfect library perhaps I missed something.
please help me

**Comment by alterx** [comment]
Hi @lovasoa 

I'm having issues that I think are related to this one. I've created a simple example to reproduce:


https://stackblitz.com/edit/nextjs-wp1uah?file=pages/index.js

This uses nextjs11 and  webpack 5, and when trying to do this:

```
 const SQL = await initSqlJs({
    locateFile: file =>
      `https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.4.0/dist/${file}`
  });
  let db = new SQL.Database();
```

I get an error:
```
Unhandled Runtime Error
RuntimeError: abort(LinkError: WebAssembly.instantiate(): Import #36 module="a" function="L" error: function import requires a callable). Build with -s ASSERTIONS=1 for more info.
``` 

I don't have a lot of experience with wasm, what could be happening here? Thanks in advance

**Comment by kylebarron** [comment]
I get the same error, below, with SQL.js 1.6.1. And SQL.js 1.6.0 makes the page hang. Luckily 1.5.0 works for me, so I'll pin to that version.

```
LinkError: WebAssembly.instantiate(): Import #0 module="a" function="a" error: function import requires a callable
```
