### ISSUE TITLE
DESCRIBE [TABLE NAME] isn't working

### ISSUE THREAD

**Issue by Kaywee27** [sql-js/sql.js#432]
I am showing a list of table names taken from a DB in a tab bar and when clicked on each tab, I am running a "SELECT * FROM [TABLE NAME]" to display the records.

However, if the table is not there in the DB already and I created it using "CREATE TABLE" query, the table is getting created, but I am not getting any result if I execute "SELECT"  query with that table name.

At least to show the columns to the user, I tried to use "DESCRIBE [TABLE NAME]" query and it says syntax error.

Am I doing anything wrong or the DESCRIBE query isn't working in this package?

**Comment by lovasoa** [comment]
sql.js is an api over sqlite. It supports the same syntax that sqlite does. DESCRIBE is not standard SQL. 

you probably want to use the sqlite_schema table. https://sqlite.org/schematab.html

**Comment by kaizhu256** [comment]
If you want to show column info, try `PRAGMA TABLE_INFO([table name])`

yes, `SELECT * FROM [table name]` won't return anything if the table is empty, which is unfortunate.

**Comment by Kaywee27** [comment]
> If you want to show column info, try `PRAGMA TABLE_INFO([table name])`
> 
> yes, `SELECT * FROM [table name]` won't return anything if the table is empty, which is unfortunate.

Hey, thank you @kaizhu256 . I can find it useful.

If it's not standard, famous platforms like [https://www.geeksforgeeks.org/sql-describe-statement/](url) should also remove that from the docs. I feel this issue lacks uniformity in the community

**Comment by Kaywee27** [comment]
> sql.js is an api over sqlite. It supports the same syntax that sqlite does. DESCRIBE is not standard SQL.
> 
> you probably want to use the sqlite_schema table. https://sqlite.org/schematab.html

@lovasoa Hey, Thanks for the quick reply

**Comment by lovasoa** [comment]
You're welcome. You should probably avoid sites like geeksforgeeks.org. You should refer to the official documentation of the RDBMS you are using. In this case: https://sqlite.org/lang.html . It's less beautiful, but more accurate.

Also, if your only need is to access the column names with your result when your table is empty, you don't have to do any of that. You should use [`Statement.getColumnNames`](https://sql.js.org/documentation/Statement.html#%255B%2522getColumnNames%2522%255D).

**Comment by KVPasupuleti** [comment]
@lovasoa 

We have a query `SELECT * FROM TABLE_NAME`

We got an empty array when executed this query using `db.exec(query)`.

As you suggested, we tried this

```JS
    var stmt = db.prepare(
        "SELECT * FROM TABLE_NAME"
    );
    stmt.step(); // Execute the statement
    console.log(stmt.getColumnNames());
```

Even though, we got [] as a result.

Is it the correct way of implementation?

Can you help us out where we went wrong?

**Comment by lovasoa** [comment]
This is not enough to reproduce your issue. If you think you found a bug, you should provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by KVPasupuleti** [comment]
@lovasoa 

Please check [this](https://codesandbox.io/s/sql-get-column-names-example-tcwjq?file=/src/sql.js) sandbox link 

I have displayed the result in the console.

**Comment by lovasoa** [comment]
Your table is just empty, the statement doesn't yield anything.

**Comment by lovasoa** [comment]
If you want to list the columns in a table, you can use 

```sql
SELECT name FROM pragma_table_info('your_table');
```
