### ISSUE TITLE
Sqlite database show different result when using different browser

### ISSUE THREAD

**Issue by boygiandi** [sql-js/sql.js#434]
I'm facing with this strange problem. I'm trying to read imessage database at `~/Library/Messages/chat.db`. 
- When I use sql.js to query `message` table. The last id is 13421. 
- But when I use `DB Browser for SQLite` (https://sqlitebrowser.org/dl/), it show the last id is 13423. https://i.imgur.com/0vPzgoe.png
- When I use chrome extension `SQLite Viewer`, it show 13421 https://i.imgur.com/QNtGG86.png
- When I use sqlite3 command line, it show 13423 https://i.imgur.com/fWLaYFV.png

I know that 13423 is correct. The sql.js and chrome extension `SQLite Viewer` somehow not update anymore. I tried to add more rows to table but they still show id 13421 as last message.
How to fix this ?

**Comment by lovasoa** [comment]
Hello! Can you post a database with which you can reproduce the issue ?
Did you make sure you were opening the exact same database and that it hadn't been modified by another software between you opening it in sql.js and the sqlite3 commandline ? sqlite3 and sql.js use the exact same library code, so they return the exact same results when you use the same sqlite version on the same file.

**Comment by boygiandi** [comment]
How to make sure that the sqlite3 and sqljs has the same version ? Because this is my imessage database, so it's hard to post it online.

**Comment by lovasoa** [comment]
```sql
select sqlite_version()
```

If this issue is not reproductible, I'll have to close it...
