### ISSUE TITLE
Use of database.prepare() appears to block "DROP TABLE" unless statement.free() is used to clean up.

### ISSUE THREAD

**Issue by DavidPratten** [sql-js/sql.js#435]
Hi,

Please consider documentation updates for database.prepare() and database.run()/exec() etc to warn users of this behaviour. Ideally the API could be changed so that statement.free() executes when the JS statement object goes out of scope.

It appears that if database.prepare() is used, without corresponding use of statement.free() that "DROP TABLE" will fail with error "Uncaught Error: database table is locked".  

The cause? It seems that SQLite has more stringent locking requirements for DROP compared to other DDL / DML statements.

Thanks

David

**Comment by lovasoa** [comment]
> Ideally the API could be changed so that statement.free() executes when the JS statement object goes out of scope.

Unfortunately this is not possible, at least not while supporting all the JavaScript versions that we do. 

> Please consider documentation updates for database.prepare() and database.run()/exec() etc to warn users of this behaviour

We do not re-document all the behavior of Sqlite, this would be a Herculean task. However, I'm open to a small PR adding a sentence about the lock in the end of the jsdoc of `Database.prepare`. Are you interested?

**Comment by DavidPratten** [comment]
Created PR.  

All the best.

David
