### ISSUE TITLE
Module not found: Error: Can't resolve 'fs' in '.../node_modules/sql.js/dist'

### ISSUE THREAD

**Issue by deski-app** [sql-js/sql.js#441]
Webpack build fails with: Module not found: Error: Can't resolve 'fs' in '.../node_modules/sql.js/dist'

Sql.js version: 1.4.1

**Comment by lovasoa** [comment]
Hello! Can you give more information? This looks more like a misconfiguration on your side than a bug in sql.js

**Comment by deski-app** [comment]
Not sure what details might be useful. I believe this might be related (other project that seems to depend on sql.js): https://github.com/marcorinck/typeorm-ionic4-test/issues/1#issuecomment-409987297

It's possible to fool webpack with.
`  externals: {
    fs: 'fs',
  },`
Yet the creation of new database with 
`var db = new SQL.Database();`
throws `OutOfMemory` error.

Funny though that when importing the debug variant it succeeds
`import sqljs from "sql.js/dist/sql-wasm-debug";`

**Comment by lovasoa** [comment]
Ok. I don't think your problem is with sql.js itself, but with the code generated by https://github.com/emscripten-core/emscripten

**Comment by thanhhai08sk** [comment]
This solved the problem for me: https://stackoverflow.com/a/65490683/5287436
