### ISSUE TITLE
lastID in sql.js

### ISSUE THREAD

**Issue by bartosz-k** [sql-js/sql.js#444]
In sqlite3 for node you can write

```
db.run("insert into ids(reference_count) values (1); ", [], function (err) {
    this.lastID // <- here
})
```

to get last ID of autoincremented field. 
Is it possible to do similar thing in sql.js? I want note that using `last_insert_rowid()`  is not good enough, because if may return incorrect results if there are multiple inserts before read.

**Comment by lovasoa** [comment]
You should always be able to use [`last_insert_rowid()`](https://www.sqlite.org/lang_corefunc.html#last_insert_rowid). 

>  because if may return incorrect results if there are multiple inserts before read.

You just have to execute it immediately after your insert statement. sql.js is not parallel, so you have full control over the order in which your statements execute.
