### ISSUE TITLE
Page Unresponsive on requesting large data

### ISSUE THREAD

**Issue by KVPasupuleti** [sql-js/sql.js#455]
## Description

When executing a query that returns a large number of records, the page is getting unresponsive. The issue is happening even if we run the execution command using workers timers

## Steps to reproduce

1. Go to sql-js [online demo](https://sql.js.org/examples/GUI/)
2. Add the database file you got using [this](https://ccbp-fullstack-backend.s3.ap-south-1.amazonaws.com/beta/intro_to_databases/assets/databases/youtube_db_v1.sqlite3
) link 

3. Run this query 

```
SELECT user_likes.user_id, user_likes.reaction_type, channel_user.user_id
 FROM user_likes INNER JOIN channel_user
 ```
 
 ## Results
### Expected
The query should run well and the results should be shown

### Actual
Page is getting unresponsive and a reload is required

### Browser
Chrome 90

**Comment by rhashimoto** [comment]
```sql
SELECT COUNT(*) FROM user_likes INNER JOIN channel_user;
   ...> 252787680
```

That's 250 _million_ rows. SQL.js can count them just fine but it doesn't have enough space to put them. Are you sure you don't mean to join ON something, like `user_id`? That result would be 3 _orders of magnitude_ smaller and still a lot to display in a browser without dynamically recycling HTML elements.

**Comment by KVPasupuleti** [comment]
What exactly does not have enough space to accommodate the records? Do you mean SQL.js or the browser?

We tried cloning your demo and just ran our query after commenting down the code where we show the result in HTML. We just expected to see the result in the console so that we can do something on top of it for our requirement. But unfortunately, we couldn't find that too and the page went unresponsive.

Is there any limitation on the number of rows we can request using `db.exec` even though we don't display them in HTML? (You know this is being done using Web Workers)

We are using SQL.js in a code playground where a user can run any kind of code to practice. In this case, the user has the freedom to run any query, hence we can't restrict him/her to not running some queries.   

How to handle this case? 

For specific queries like `SELECT * from TABLE_NAME`, we are appending LIMIT and OFFSET and giving a pagination experience to the user.

But, how can we handle various other queries?

Is there any solution to get this working or do we have any alternative like pagination?

**Comment by lovasoa** [comment]
You can use a statement iterator to retrieve the result rows one by one instead of all at once. This lets you retrieve exactly the number of rows you want.
