### ISSUE TITLE
Adding Custom Extensions to sql.js

### ISSUE THREAD

**Issue by twoxfh** [sql-js/sql.js#459]
Great project, I am using @Taytay development environment which makes it super easy to build sql.js. I am trying to add extensions from ext/misc such as series into sql.js. I added series.c to the sqlite-src/sqlite-amalgamation folder and modified the Makefile:

```
out/series.bc: sqlite-src/$(SQLITE_AMALGAMATION)
 	mkdir -p out
 	$(EMCC) $(CFLAGS) -s LINKABLE=1 -c sqlite-src/$(SQLITE_AMALGAMATION)/series.c -o $@
```

and 

`BITCODE_FILES = out/sqlite3.bc out/extension-functions.bc out/series.bc`

This successfully compiles, but I cannot run query on SQLite, `SELECT value FROM generate_series(5,100,5)` it says the generate_series doesnt exist. I also added "_sqlite3_series_init" to exported_functions, however, that did not change anything, 

Can anyone shed some light on adding custom extensions?

**Comment by kaizhu256** [comment]
maybe delete the `OMIT_LOAD_EXTENSION` flag?  was added in [commit 8aed8927](https://github.com/sql-js/sql.js/commit/8aed8927a8d6eb1f99dae087b9db58d0216bacd9#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R4), i'm guessing to reduce filesize

```diff
diff --git a/Makefile b/Makefile
index 9aeed3b..2038f86 100644
--- a/Makefile
+++ b/Makefile
@@ -19,7 +19,6 @@ EMCC=emcc

 CFLAGS = \
        -O2 \
-       -DSQLITE_OMIT_LOAD_EXTENSION \
        -DSQLITE_DISABLE_LFS \
        -DSQLITE_ENABLE_FTS3 \
        -DSQLITE_ENABLE_FTS3_PARENTHESIS \
```

**Comment by rhashimoto** [comment]
I think `SQLITE_OMIT_LOAD_EXTENSION` is for dynamically loaded extensions, and the OP is trying to add an extension statically.

My guess is they need to call the extension [initialization function](https://github.com/sqlite/sqlite/blob/f9ac1ab1e7fd9cb827094a88c894d595aacb4927/ext/misc/series.c#L429), just as the standard extensions initialization function is [exported](https://github.com/sql-js/sql.js/blob/1223603d1e1db658a9d325ebf92d95906b04149d/src/exported_functions.json#L44) (as already done), [wrapped](https://github.com/sql-js/sql.js/blob/f5d9f5482c52870b41e00d1ab9de3834b4c8b8c8/src/api.js#L227-L231), and [called](https://github.com/sql-js/sql.js/blob/f5d9f5482c52870b41e00d1ab9de3834b4c8b8c8/src/api.js#L795).

**Comment by twoxfh** [comment]
@rhashimoto @kaizhu256 thanks for your feedback! @rhashimoto read my mind, and it works. Thanks for your help!

**Comment by KevBelisle** [comment]
@twoxfh It's been a few years, but it'd be great to see what changes you made exactly to get this working.

If you have a fork/branch with your changes that I could compare to main, it'd be much appreciated!

**Comment by twoxfh** [comment]
> [@twoxfh](https://github.com/twoxfh) It's been a few years, but it'd be great to see what changes you made exactly to get this working.
> 
> If you have a fork/branch with your changes that I could compare to main, it'd be much appreciated!

[Sqliteviz](https://github.com/lana-k/sqliteviz/tree/master/lib/sql-js) does something similar, their repo would likely better.
