### ISSUE TITLE
How to integrate with Vite?

### ISSUE THREAD

**Issue by jotyy** [sql-js/sql.js#467]
I'm currently working with Vite instead of Webpack, but I have no idea about how to integrate sql.js with Vite.

**Comment by lovasoa** [comment]
see https://vitejs.dev/guide/assets.html#explicit-url-imports

Use an import to get an url from the wasm file of the node module, then specify the url in initSqlJs

**Comment by 29decibel** [comment]
For someone's wondering, this is all you need:
```ts
import workletURL from "sql.js/dist/sql-wasm.wasm?url";
const SQL = await initSqlJs({ locateFile: (file) => workletURL });
```

**Comment by Gladskih** [comment]
> For someone's wondering, this is all you need:
> 
> ```ts
> import workletURL from "sql.js/dist/sql-wasm.wasm?url";
> const SQL = await initSqlJs({ locateFile: (file) => workletURL });
> ```

This does not seem to work.
> Uncaught ReferenceError ReferenceError: initSqlJs is not defined

**Comment by capaj** [comment]
I am getting `NotFoundError: A requested file or directory could not be found at the time an operation was `

using vite 6.1.1
