### ISSUE TITLE
Import CSV

### ISSUE THREAD

**Issue by var-kar** [sql-js/sql.js#468]
Is there a way to quickly import a CSV? Something like this?  https://www.sqlite.org/csv.html

I know I can read the datatypes of columns and write a create script and use insert statement. But it is not the more efficient way to load a csv to db who has millions of rows.

Any better way to do this via SQLjs?

Many thanks,

**Comment by lovasoa** [comment]
No, there is no csv module included in sql.js.

**Comment by mwenge** [comment]
I have a quick and dirty solution to this at https://mwenge.github.io/sql.js/examples/GUI/

It uses a slightly modified version of the file referenced at https://www.sqlite.org/csv.html. Seems to work well even with very large (2m+ record) csv files.
