### ISSUE TITLE
initSqlJs is not a function, require(sq-wasm.js) loads as Module in Electron

### ISSUE THREAD

**Issue by jmw992** [sql-js/sql.js#475]
I'm getting a "initSqlJs is not a function" error when I try to use the code example laid out in the github landing page for initiating a SQL instance.  It does appear that that initSQL is getting loaded in as a module instead as a function.  Clicking through the module __proto__ functions I'm not seeing any initSQL or relevant functions unfortunately.

![image](https://user-images.githubusercontent.com/15371018/130661730-1442ed0d-17dd-455e-9cd4-6b0e2378c05c.png)

I have been able to get this to work if I add the module npm package and add the following to the top of the file, however that is causing some issues in my webpack bundler in my dev environment :(
```js
import { createRequire } from 'module';
const require = createRequire(import.meta.url);
```

**Comment by lovasoa** [comment]
We do not support direct import as an ES module yet

**Comment by jmw992** [comment]
Ok thanks for the info.  The fix which ended up fixing sidestepping the webpack bundler error was just giving the `require` function a different name when using the `module` npm package.  It must have been a name clashing issue.  So now everything looks like the following and it's working for me.

```js
import { createRequire } from 'module';
const importRequire = createRequire(import.meta.url);

export async function readDbFile(filename) {
  var initSqlJs = importRequire(`sql.js`);
  let d= undefined;
  try {
    await initSqlJs().then(function (SQL) {
      var data = fs.readFileSync(filename);
      var sqldb = new SQL.Database(data);
      ...
    });
  } catch (e) {
    ...
  }
  ...
}

```
