### ISSUE TITLE
Treat integer type as string in query results

### ISSUE THREAD

**Issue by westito** [sql-js/sql.js#483]
JavaScript doesn't support 64bit integers, but SQLite does. I know there is a new "BigInt" feature in SQL.js, but it isn't compatible with some browsers. It is possible to store integer as integer type in the database, but read as string to JavaScript? My idea is to convert it on application level. I use dart2js that have a "BigInt" type (what is not the same as the JavaScript BigInt). It can convert string to BigInt at application level. Because I can read integer as JavaScript integer only in sql.js, the number lose its precision before I can use dart's BigInt.

**Comment by lovasoa** [comment]
We do support BigInts in sql.js (since recently), but we don't want to make everyone pay the price of the conversion when it is not needed. If you want to convert a number to a string, you can do it in SQL directly.
