### ISSUE TITLE
Error in documentation/Database.html

### ISSUE THREAD

**Issue by salix5** [sql-js/sql.js#498]
https://sql.js.org/documentation/Database.html
> Uncaught TypeError: classList[(classList.length - 1)] is undefined
    <anonymous> https://sql.js.org/documentation/scripts/misc.js:70
    <anonymous> https://sql.js.org/documentation/scripts/misc.js:82

Line 70: 
```javascript
var langName = classList[classList.length - 1].split('-')[1];
```

Maybe it should be:
```javascript
var langName = classList.length ? classList[classList.length - 1].split('-')[1] : undefined;
```

**Comment by salix5** [comment]
https://github.com/salix5/sql.js-mirror/commit/ab9edb09db9c87a68efe6269f21ecaeae1b16111

**Comment by lovasoa** [comment]
The documentation is built automatically. This looks like a bug in jsdoc, not sql.js.

https://github.com/jsdoc/jsdoc
