### ISSUE TITLE
SQLite 3.38.0

### ISSUE THREAD

**Issue by fuintis** [sql-js/sql.js#502]
SQLite just release the 3.38.0 version, that includes, among other features, the inclusion of JSON1 functions as built-ins. Also supports [the -> and ->> operators](https://sqlite.org/json1.html#jptr).

Any plans on releasing sql.js with the latest version of SQLite?

Many thx in advance.

**Comment by jonasb** [comment]
sqlite3 3.38.5 is included in https://github.com/sql-js/sql.js/releases/tag/v1.7.0
