### ISSUE TITLE
[Help] Error: out of memory at SQL.Database()

### ISSUE THREAD

**Issue by vicentecastroa** [sql-js/sql.js#505]
Hi, I need some help. 
I'm developing a Vue.js app and I'm trying to run a sqlite database on a page. I followed the instructions from the README and I'm getting an error when initializing a new database. 
```javascript
import initSqlJs from "sql.js";
...
createDatabase(){
    initSqlJs({ locateFile: (file) => `https://sql.js.org/dist/${file}` }).then((SQL) => {
        console.log("SQL", SQL);
        this.dbSql = new SQL.Database();
        console.log("dbSQL", this.dbSql);
}
```

In the console I'm getting this error: `Uncaught (in promise) Error: out of memory`
![image](https://user-images.githubusercontent.com/13738469/162080755-bd6fddf1-1065-4e4e-a80c-4ab82324ebd0.png)

I don't know how can I tackle this error. Appreciate it if someone can help me 🙏.

**Comment by vicentecastroa** [comment]
This helped me. (From https://github.com/sql-js/sql.js/issues/467)
> see https://vitejs.dev/guide/assets.html#explicit-url-imports
> 
> Use an import to get an url from the wasm file of the node module, then specify the url in initSqlJs

**Comment by lastmjs** [comment]
Hi, how did that resolve your problem? I am also running into this issue but I am using `sql-asm.js`, so I don't think there's a problem with me loading from the wrong url since I don't need to load a Wasm file.
