### ISSUE TITLE
New compiled version? 3.38.4

### ISSUE THREAD

**Issue by ironboy** [sql-js/sql.js#507]
Would it be possible for you to compile version 3.38.4?

(And in general to compile new versions of SQLite to sql.js a bit more often, alternatively outline how do it yourself.)

**Comment by jonasb** [comment]
sqlite3 3.38.5 is included in https://github.com/sql-js/sql.js/releases/tag/v1.7.0

**Comment by ironboy** [comment]
Thank you Jonas! Much appreciated!
