### ISSUE TITLE
add Emscripten build SINGLE_FILE parameter

### ISSUE THREAD

**Issue by sunwanxin213** [sql-js/sql.js#515]
Someone server cannot set mime type, so SINGLE_FILE can output only one .js file.
this will be very useful.

**Comment by lovasoa** [comment]
The asm build already consists of a single file. Have a look at the release files.

**Comment by sunwanxin213** [comment]
SINGLE_FILE actually uses the base64 expression of wasm, which is different from the principle of asm.js.

**Comment by sunwanxin213** [comment]
Okay...... Finally, just convert sql-wasm.wasm to base64 and replace it with the path to sql-wasm.wasm in sql-wasm.js.

**Comment by sunwanxin213** [comment]
[Sql.zip](https://github.com/sql-js/sql.js/files/8881823/Sql.zip)
