### ISSUE TITLE
Replace JSDoc as it is not maintained and is legacy software

### ISSUE THREAD

**Issue by ShukantPal** [sql-js/sql.js#520]
Hi folks, JSDoc is [no longer being actively maintained](https://github.com/jsdoc/jsdoc/commits/main) and that's why I built a better, maintainable toolset called [webdoc](https://www.webdoclabs.com?utm_campaign=melonjs&utm_source=ni&utm_medium=GitHub). webdoc has a more [modern theme](https://webdoc-labs.github.io/example-documentation/index.html) that's fully customizable! I would be down to helping you move your documentation to webdoc, the choice is up to you.

I think webdoc will bring a lot of clarity to your existing documentation, and it is pretty good for this use case. See melonJS [docs](http://melonjs.github.io/melonJS/docs/), which are built with webdoc now!

**Comment by lovasoa** [comment]
Github issues are not the right place for advertising your proprietary product.
