### ISSUE TITLE
Usage with Webassembly.instantiate

### ISSUE THREAD

**Issue by creativiii** [sql-js/sql.js#530]
So recently [Vercel has announced they support `wasm` in their serverless functions](https://vercel.com/docs/concepts/edge-network/wasm) which led me to wonder if I could simply load `sql.js` in a serverless function and return data from an endpoint.

I've been able to get [their official example building correctly](https://github.com/vercel/examples/blob/main/edge-api-routes/wasm-rust-xor/api/xor.ts), but when trying to import `sql-wasm.wasm` I get the following error on build.

(I downloaded `sql-wasm.wasm` from the CDN and have it locally on my fs)

```
Failed to compile.
14:24:16.061 |  
14:24:16.062 | ./lib/sql-wasm.wasm?module
14:24:16.062 | Module not found: Can't resolve 'a' in '/vercel/path0/lib'
14:24:16.062 |  
14:24:16.062 | Import trace for requested module:
14:24:16.062 | ./pages/api/hello.ts
```

```hello.ts

import type { NextApiRequest, NextApiResponse } from "next";
// @ts-ignore
import wasm from "../../lib/sql-wasm.wasm?module";

export const config = {
  runtime: "experimental-edge",
};

export default async function handler(
  request: NextApiRequest,
  res: NextApiResponse
) {
  const { exports } = (await WebAssembly.instantiate(wasm)) as any;

  res.status(200).json({ info: exports });
}
```

I'm not the utmost expect with wasm so I'm not entirely sure why instantiating one wasm file works while this one breaks. 

Any ideas?

**Comment by lovasoa** [comment]
You are not supposed to use the raw wasm file directly, but use the sql.js library instead.
You should probably ask for help with Vercel instead of here.
