### ISSUE TITLE
Pre-compiling SQL queries

### ISSUE THREAD

**Issue by rbalicki2** [sql-js/sql.js#533]
Hi folks!

Apologies if there's a better place to ask these basic questions. I haven't gotten my hands dirty with SQL.js. Happy to move this to a discord, if there is one, or ask in another channel!

* Does sql.js support pre-compiling SQL queries? e.g. if I know that I will be calling `select * from users`, I'd like to (at build time) pre-compile that SQL statement into (presumably) a JSON representation of the query plan. Is this feasible?
* The wasm file, sql-wasm.wasm, is 263kb with brotli encryption. Is there a path toward making that smaller, e.g. LTO, compiling sqlite without certain features, etc.?

Thank you!

**Comment by lovasoa** [comment]
> Does sql.js support pre-compiling SQL queries? e.g. if I know that I will be calling select * from users, I'd like to (at build time) pre-compile that SQL statement into (presumably) a JSON representation of the query plan. Is this feasible?

No it's not. But you are worrying about the wrong things. The time it will take to prepare your sqlstatements is negligible when compared to the time it will take to download and parse sqlite itself.

> The wasm file, sql-wasm.wasm, is 263kb with brotli encryption. Is there a path toward making that smaller, e.g. LTO, compiling sqlite without certain features, etc.?

This is the right thing to worry about :) You can have a look at other issues and PR if you want to help there.

**Comment by rbalicki2** [comment]
Thanks for the info!

For those who stumble upon this thread in the future, I'll clarify one thing. I was hoping to use SQL.js with only precompiled queries. This would allow for never downloading and parsing the query parser code, and (potentially a bigger deal) never downloading information about the schema.

The comparison isn't perfect, of course, but in Relay (a GraphQL client), we pre-compile reader and writer artifacts for each query. Initial tests indicated that writing data to the Relay store using these pre-compiled artifacts was ~10x faster. But more importantly, the front-end doesn't require knowledge of the GraphQL schema, which can be massive.

**Comment by kaizhu256** [comment]
> I was hoping to use SQL.js with only precompiled queries. This would allow for never downloading and parsing the query parser code

- no, you still need the parser --  there's no way to to create a precompiled-query during compile-time.
- a precompiled-query can only be created during runtime after:
  1. downloading sql.js
  2. creating a new sqlite-instance during runtime
  3. calling [sqlite3_prepare_v2(...)](https://www.sqlite.org/c3ref/stmt.html) on the newly-created sqlite-instance
      - which requires the parser to be included with sql.js

- the c-struct of the precompiled-query is provided below, showing it requires a pointer to runtime sqlite-instance.

```c
/*
** An instance of the virtual machine.  This structure contains the complete
** state of the virtual machine.
**
** The "sqlite3_stmt" structure pointer that is returned by sqlite3_prepare()
** is really a pointer to an instance of this structure.
*/
struct Vdbe {
  sqlite3 *db;            /* The database connection that owns this statement */
  Vdbe *pPrev,*pNext;     /* Linked list of VDBEs with the same Vdbe.db */
  Parse *pParse;          /* Parsing context used to create this Vdbe */
  ynVar nVar;             /* Number of entries in aVar[] */
  u32 iVdbeMagic;         /* Magic number defining state of the SQL statement */
  int nMem;               /* Number of memory locations currently allocated */
  int nCursor;            /* Number of slots in apCsr[] */
  u32 cacheCtr;           /* VdbeCursor row cache generation counter */
  int pc;                 /* The program counter */
  int rc;                 /* Value to return */
  i64 nChange;            /* Number of db changes made since last reset */
  int iStatement;         /* Statement number (or 0 if has no opened stmt) */
  i64 iCurrentTime;       /* Value of julianday('now') for this statement */
  i64 nFkConstraint;      /* Number of imm. FK constraints this VM */
  i64 nStmtDefCons;       /* Number of def. constraints when stmt started */
  i64 nStmtDefImmCons;    /* Number of def. imm constraints when stmt started */
  Mem *aMem;              /* The memory locations */
  Mem **apArg;            /* Arguments to currently executing user function */
  VdbeCursor **apCsr;     /* One element of this array for each open cursor */
  Mem *aVar;              /* Values for the OP_Variable opcode. */

  /* When allocating a new Vdbe object, all of the fields below should be
  ** initialized to zero or NULL */

  Op *aOp;                /* Space to hold the virtual machine's program */
  int nOp;                /* Number of instructions in the program */
  int nOpAlloc;           /* Slots allocated for aOp[] */
  Mem *aColName;          /* Column names to return */
  Mem *pResultSet;        /* Pointer to an array of results */
  char *zErrMsg;          /* Error message written here */
  VList *pVList;          /* Name of variables */
#ifndef SQLITE_OMIT_TRACE
  i64 startTime;          /* Time when query started - used for profiling */
#endif
#ifdef SQLITE_DEBUG
  int rcApp;              /* errcode set by sqlite3_result_error_code() */
  u32 nWrite;             /* Number of write operations that have occurred */
#endif
  u16 nResColumn;         /* Number of columns in one row of the result set */
  u8 errorAction;         /* Recovery action to do in case of an error */
  u8 minWriteFileFormat;  /* Minimum file format for writable database files */
  u8 prepFlags;           /* SQLITE_PREPARE_* flags */
  u8 doingRerun;          /* True if rerunning after an auto-reprepare */
  bft expired:2;          /* 1: recompile VM immediately  2: when convenient */
  bft explain:2;          /* True if EXPLAIN present on SQL command */
  bft changeCntOn:1;      /* True to update the change-counter */
  bft runOnlyOnce:1;      /* Automatically expire on reset */
  bft usesStmtJournal:1;  /* True if uses a statement journal */
  bft readOnly:1;         /* True for statements that do not write */
  bft bIsReader:1;        /* True for statements that read */
  yDbMask btreeMask;      /* Bitmask of db->aDb[] entries referenced */
  yDbMask lockMask;       /* Subset of btreeMask that requires a lock */
  u32 aCounter[9];        /* Counters used by sqlite3_stmt_status() */
  char *zSql;             /* Text of the SQL statement that generated this */
#ifdef SQLITE_ENABLE_NORMALIZE
  char *zNormSql;         /* Normalization of the associated SQL statement */
  DblquoteStr *pDblStr;   /* List of double-quoted string literals */
#endif
  void *pFree;            /* Free this when deleting the vdbe */
  VdbeFrame *pFrame;      /* Parent frame */
  VdbeFrame *pDelFrame;   /* List of frame objects to free on VM reset */
  int nFrame;             /* Number of frames in pFrame list */
  u32 expmask;            /* Binding to these vars invalidates VM */
  SubProgram *pProgram;   /* Linked list of all sub-programs used by VM */
  AuxData *pAuxData;      /* Linked list of auxdata allocations */
#ifdef SQLITE_ENABLE_STMT_SCANSTATUS
  i64 *anExec;            /* Number of times each op has been executed */
  int nScan;              /* Entries in aScan[] */
  ScanStatus *aScan;      /* Scan definitions for sqlite3_stmt_scanstatus() */
#endif
};
```
