### ISSUE TITLE
Convert sql-wasm.wasm to base64 and embed in HTML/JavaScript

### ISSUE THREAD

**Issue by SMUsamaShah** [sql-js/sql.js#547]
Is there a way to convert `sql-wasm.wasm` to base64 such that it can then be embedded directly in JavaScript and loaded from base64 string. 

I want to use `sqlite-wasm` from html file locally without needed a server. I converted it to base64 here https://gist.github.com/SMUsamaShah/358fba159cb41fe469fc61e7db444c0e (which may or may not be correct) but all attempts at loading that string as wasm module have been a failure.

**Comment by lovasoa** [comment]
You can even go better then that. See https://github.com/lovasoa/bin2png

**Comment by SMUsamaShah** [comment]
I am going to give this a try and will update with another response but I feel like even this won't resolve it. When I load from base64 I get `Uncaught (in promise) TypeError: WebAssembly.instantiate(): Import #0 module="a" error: module is not an object or function` which I found out means wasm module needs something else too. https://stackoverflow.com/questions/75839317/how-do-i-load-sql-js-wasm-as-base64-so-that-it-can-be-loaded-directly-in-html-fi

**Comment by SMUsamaShah** [comment]
Your PNG method worked, thanks for pointing out. But why go through PNG conversion and back when you have wasm as base64 string.

From your code I found out i was supposed to use `initSqlJs` instead of calling `WebAssembly.instantiate` directly.

Then I used https://github.com/BillKek/wasm2js_let_static to convert `sql-wasm.wasm v1.8.0` to base64 again. New base64 is correct one.

Then loaded it like this

```javascript
    const wasm_strbuffer = atob(SQLBASE64);
    let wasm_codearray = new Uint8Array(wasm_strbuffer.length);
    for (var i in wasm_strbuffer) wasm_codearray[i] = wasm_strbuffer.charCodeAt(i);

    const sqlPromise = initSqlJs({
        locateFile: filename => URL.createObjectURL(new Blob([wasm_codearray], { type: 'application/wasm' }))
    });
    const dataPromise = fetch("mysqlite.db").then(res => res.arrayBuffer());
    Promise.all([sqlPromise, dataPromise]).then((data) => {
        const SQL = data[0];
        const buf = data[1];
        const db = new SQL.Database(new Uint8Array(buf));
        dbLoaded(db);
    });
```

and it just works.

Base64 wasm gist https://gist.github.com/SMUsamaShah/358fba159cb41fe469fc61e7db444c0e

**Comment by lovasoa** [comment]
The question is why go to base64 and back when you can encode as a png instead?

 - PNG compresses the data, whereas base64 makes it larger. 
 - PNG can be efficiently decoded in the background whereas base64 decoding blocks the main thread.

**Comment by lovasoa** [comment]
Additionally, in your example, you decode the base64 to a js string, then copy the data to an uint8array, and immediately deallocate the large js string you just allocated. This is inefficient both in term of cpu and memory usage.

**Comment by SMUsamaShah** [comment]
You are right, don't disagree with you. But with my use case, I don't need to worry about size or blocking the main thread at all, mainly because it's a one time operation. 

Only reason I was interested in embedding it in html is so that I can double click open the html file in the browser, which means I have no reason worry about size anyway.

If I was re
