### ISSUE TITLE
How to use in Vite?

### ISSUE THREAD

**Issue by mtdvlpr** [sql-js/sql.js#548]
I am using Nuxt3 with Vite. I have the following code:
```javascript
import wasmUrl from '@/public/sql-wasm.wasm?url'

const { default: sqljs } = await import('sql.js')
const SQL = await sqljs({
  locateFile: () => wasmUrl,
})
```

I get the following error:
```javascript
TypeError: Cannot set properties of undefined (setting 'exports')
    at sql-wasm.js:95:451
```

When I use the below config I get the error that `sqljs` is undefined and therefore not a function.
```javascript
vite: {
  build: {
    rollupOptions: {
      external: [/node_modules\/sql\.js\/dist\/sql-wasm\.js$/],
    },
  },
},
```

Am I missing something?

**Comment by lovasoa** [comment]
This is more a question than an issue, I'm closing it, but feel free to discuss below.

**Comment by 4www** [comment]
Adding for ref, [answered here](https://github.com/sql-js/sql.js/issues/467#issuecomment-2015608979).
