### ISSUE TITLE
Read/Write files in HTML

### ISSUE THREAD

**Issue by JagritParakh** [sql-js/sql.js#550]
I want to directly read/write to a pre-existing .sqlite file directly in HTML. Can anyone help me?

**Comment by lixingyangok** [comment]
I have tried this. I used indexedDB (Dexie.js) to persist the data which come from sql.export() in browser. 
so after the user refresh the browser, it will not cause data lossing

**Comment by lovasoa** [comment]
Hi ! 
  It's not clear exactly what you want.
  If your sqlite file is located on a server and shouldn't be publically accessible, then the modifications should happen on the server side and you probably don't need sql.js.

  If the changes to the file should stay local to each client loading your website, then you can use sql.js, download the sqlite file in javascript, pass it to `new SQL.Database(uint8array)`, and then export it with `db.export()` and save it, in local storage or indexeddb for instance.
