### ISSUE TITLE
How can you create a table with blob values?

### ISSUE THREAD

**Issue by marcusx2** [sql-js/sql.js#553]
Blobs are basically arrays or uint8arrays right? I want to do something like

```
let sqlstr = "CREATE TABLE hello (a int, b blob); \
INSERT INTO hello VALUES (false, [124,523]); \
INSERT INTO hello VALUES (true, [12455, 938]);";
```

but it doesn't work. How can I create a table with blob values? 

Also, does [SqlValue](https://sql.js.org/documentation/api.js.html#line280) only include Uint8Array? What about other types of array? What if I have an int32 array?

Thanks!

**Comment by lovasoa** [comment]
You can [bind](https://sql.js.org/documentation/Statement.html#%5B%22bind%22%5D) an Uint8Array to your insert statement to insert a blob.

The Uint8Array should contain the raw bytes of the data you are inserting. Bytes are 8-bit values, hence the UInt8Array requirement. If you have a big-endian Int32Array, you can access its raw bytes with:

```js
b = new Int32Array([1,2,3, 0xffff])
// -> Int32Array(4) [ 1, 2, 3, 65535 ]

new Uint8Array(b.buffer)
// -> Uint8Array(16) [ 1, 0, 0, 0, 2, 0, 0, 0, 3, 0, … ]

**Comment by marcusx2** [comment]
@lovasoa can you give me a complete example? On the [Usage](https://github.com/sql-js/sql.js#usage) section, you have this

```
let sqlstr = "CREATE TABLE hello (a int, b char); \
INSERT INTO hello VALUES (0, 'hello'); \
INSERT INTO hello VALUES (1, 'world');";
db.run(sqlstr); // Run the query without returning anything

// Prepare an sql statement
const stmt = db.prepare("SELECT * FROM hello WHERE a=:aval AND b=:bval");

stmt.bind([0, 'hello']);
```

If I try

```
 var stmt2 = db.prepare("UPDATE hello SET a=@newval");
stmt2.bind({ '@newval': new Uint8Array([1, 2, 3, 5]) });

console.log(db.exec("SELECT * FROM hello"));
```

it doesn't work.

Thank you for your time!

**Comment by lovasoa** [comment]
Just binding a value doesn't execute the statement. See 
https://sql.js.org/documentation/Statement.html#%5B%22run%22%5D

**Comment by marcusx2** [comment]
@lovasoa It worked! However...does this mean that I can bind any value regardless of the type I declared when creating the table? Table hello is supposed to be an _int_ followed by a _char_...

**Comment by lovasoa** [comment]
https://www.sqlite.org/datatype3.html
