### ISSUE TITLE
An update requirement for `using fetch loading a database from a server`

### ISSUE THREAD

**Issue by NanaVan** [sql-js/sql.js#557]
The original [example](https://github.com/sql-js/sql.js#using-fetch) for `Promise.all ` and `await` can not work functionally together (see [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all#asynchronicity_or_synchronicity_of_promise.all) for details.).
A new example can be adopted as:
```js
async function fetchSQL(){
    const [SQL, buf] = await Promise.all([
        initSqlJs({locateFile: file => `https://path/to/your/dist/folder/dist/${file}`}), 
        fetch("/path/to/database.sqlite").then(res => res.arrayBuffer())
    ]);
    const db = new SQL.Database(new Uint8Array(buf));
    // other command as below
}
fetchSQL();
```

**Comment by lovasoa** [comment]
This is not a valid bug report. Please give details about what you think the problem is. I don't see an issue with the example code you gave.

**Comment by NanaVan** [comment]
The code block I gave is the corrected one.
The [original example](https://github.com/sql-js/sql.js#using-fetch):
```js
const sqlPromise = initSqlJs({
  locateFile: file => `https://path/to/your/dist/folder/dist/${file}`
});
const dataPromise = fetch("/path/to/database.sqlite").then(res => res.arrayBuffer());
const [SQL, buf] = await Promise.all([sqlPromise, dataPromise])
const db = new SQL.Database(new Uint8Array(buf));
```
will raise an error as `SyntaxError: await is only valid in async functions, async generators and modules` as shown in [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Bad_await#async_callbacks).

That's why I recomment to update the example for fetch in browser.

**Comment by lovasoa** [comment]
Oh, I get what you are saying. It seemed evident to me that the given example had to be run in an async context (which is now supported at the root level in many places, including node). If you want to add a note to specify that (without changing the code snippet), I'll accept a pull request :)
