### ISSUE TITLE
New release with recent sqlite version

### ISSUE THREAD

**Issue by barbogast** [sql-js/sql.js#559]
Hi there,

first of all, thanks a ton for this awesome project. I'm using it to build an in-browser analytics tool, and it works really well :-)

Would it be possible to create a new release which upgrades the version of sqlite. This library uses 3.39 and the most recent version is 3.44.

Would be great, recent sqlite versions have added quite some features.

**Comment by lovasoa** [comment]
I made the update

**Comment by barbogast** [comment]
Awesome, thanks a lot.
