### ISSUE TITLE
limit keyword is ignored when using parameters.

### ISSUE THREAD

**Issue by Gamepro5** [sql-js/sql.js#562]
when running 
```
db.exec(`select l_name from library where l_librarykey = @libkey limit 1`, {'@libKey' : 1})
```

the outputted values are different than

```
db.exec(`select l_name from library where l_librarykey = `+1+` limit 1`)
```
in the sense that the subquery just completely ignores the limit instruction when using the parameter system.

I have no clue why this happens and have wasted 3 hours trying to fix this. I am certain it is not on my end.

The first piece of code is incorrect and the second gives the expected return values.

**Comment by lovasoa** [comment]
Can you provide a small self-contained  reprodution ? sql.js has a large library of tests that are continuously run, that include tests for parameter bindings

**Comment by lovasoa** [comment]
I cannot reproduce.
Just tried on https://sql.js.org/examples/GUI/

```js
worker.postMessage({
      id: 2,
      action: "exec",
      sql: "select l_name from library where l_librarykey = @libkey limit 1",
      params: { "@libkey": 1 }
});
worker.onmessage = (x) => console.log(x.data)
```

```json
{
  "id": 2,
  "results": [
    {
      "columns": [
        "l_name"
      ],
      "values": [
        [
          "Library#1"
        ]
      ]
    }
  ]
}
```

**Comment by Gamepro5** [comment]
Does it do that if you replace the post message thing with 
```
db.exec(`select l_name from library where l_librarykey = @libkey limit 1`, {'@libKey' : 1})
```

**Comment by lovasoa** [comment]
The post message thing does exactly that.

**Comment by Gamepro5** [comment]
Yeah, I also don't know why it isn't being reproduced on your end. The class I needed this for is over though, so I don't really care anymore. Sorry for bothering you.
