### ISSUE TITLE
Binding not working with json field

### ISSUE THREAD

**Issue by linhttbk97** [sql-js/sql.js#567]
Hi, I have problem that's weird. I have table CyxjFTjWPhj_WWpoLwqI that has two columns : id Text Primary key, data Text ( in json format)
For same query: 
With binding "?"
`SELECT id,data FROM CyxjFTjWPhj_WWpoLwqI WHERE json_extract(data,'$._status') != 'deleted' AND json_extract(data,'$.fKRCliNx') GLOB ? ORDER BY json_extract(data,'$.created_at') ASC `
Binding value: "`*John*`"
return empty result
But for query: 
`SELECT id,data FROM CyxjFTjWPhj_WWpoLwqI WHERE json_extract(data,'$._status') != 'deleted' AND json_extract(data,'$.fKRCliNx') GLOB '*John*'  ORDER BY json_extract(data,'$.created_at') ASC`
return result as expected

**Comment by lovasoa** [comment]
Can you provide a small self-contained reproduction?

**Comment by linhttbk97** [comment]
That happened on every single run, i'm using 1.10.2 version

**Comment by lovasoa** [comment]
Can you create a repository that depends only on sql.js contains a minimal amount of code (maybe just a single select) and illustrates the issue?

**Comment by linhttbk97** [comment]
I could be my issue, closed as it is invalid
