### ISSUE TITLE
Wasi

### ISSUE THREAD

**Issue by lastmjs** [sql-js/sql.js#569]
Hi, I'm new to the library, but I would really like to be able to use it in our environment for a lot of applications. It seems that the memory model is very limited. Could we not compile SQLite to Wasi so that it could take advantage of the filesystem from the host environment? SQL.js could provide a default host implementation that is just an array of memory like it is currently doing...or perhaps wasi just becomes another way to load like we have wasm and asm currently.

Is this feasible? My team might be able to do the work if this sounds like a good idea. I would love some feedback.

Unfortunately I can't even get SQL.js with asm.js to run in our environment even though it was just working about a week ago, I could really use some help here: https://github.com/sql-js/sql.js/issues/568

**Comment by lovasoa** [comment]
Hi!
  It's definitely possible to compile sqlite to wasi, but it's out of scope for sql.js. If you start your own project, I'd be happy to link to it in the readme here

**Comment by lastmjs** [comment]
Hi, I mean compiling sqlite to Wasi and having that binary as one of the officially supported in SQL.js. Is that out of scope? So you could import `sql-wasm.js` or `sql-wasi.js`.

Wouldn't this make SQL.js much more useful by allowing devs to hook into a filesystem for persistence?

**Comment by lovasoa** [comment]
I think the use of js + wasi is anecdotal. When you are targeting wasi, most of the time you can use sqlite directly.
