### ISSUE TITLE
The PROCEDURE keyword is not supported when running on the Online SQL interpreter."

### ISSUE THREAD

**Issue by kylewuyinhai** [sql-js/sql.js#570]
When running 
`CREATE PROCEDURE GetUsers()
      AS
      BEGIN
        SELECT * FROM xxx;
      END;
    ;`
on the website https://sql.js.org/examples/GUI/index.html, 
it displays a syntax error for the PROCEDURE keyword.

How can I support PROCEDURE?

**Comment by lovasoa** [comment]
PROCEDURE is not a valid keywork in SQLite.

However, it has 
 - [`TRIGGER`s](https://sqlite.org/lang_createtrigger.html), and
 - [user-defined functions](https://sql.js.org/documentation/Database.html#%5B%22create_function%22%5D)
