### ISSUE TITLE
Create a visualizer for SQL

### ISSUE THREAD

**Issue by krishnagogada** [sql-js/sql.js#573]
I want to create an SQL visualizer like this https://animatesql.com/

Is there any way to get the data for a SQL query execution step by step, So that I can achieve this visualizer? 

For example, there is an SQL query using WHERE clause with some condition? 
Using SQL.js is there any way to get the execution flow step-by-step like checking each row as shown in the [Animate SQL]( https://animatesql.com/).

**Comment by lovasoa** [comment]
Building something like this, but making it support the entire SQLite syntax is kind of a large undertaking. 
Real sql engines such as sqlite (which powers sql.js) do not execute queries the way it is illustrated in the animatesql you mention, at least most of the time. They do not loop over each database row to build the response.

The website you give implements just a tiny subset of sql, which is enough to illustrate what it needs to show, but building a visualizer for the sqlite query engine is orders of magnitude more complex. 

If you are very motivated, you could start by reading https://www.sqlite.org/opcode.html
