### ISSUE TITLE
file is not a database

### ISSUE THREAD

**Issue by arezhz** [sql-js/sql.js#579]
I have a Mbtiles file and I want to read that with sql.js but when I did run a query, I got an error.

```
function (buffer: ArrayBuffer) {
    initSqlJs({
        locateFile: (file) => `/src/assets/sql/${file}`,
    }).then((SQL) => {
        this._db = new SQL.Database(new Uint8Array(buffer));
        console.log(this._db.exec("select * from map")); // error is here
       }
    })
}
```

buffer: I take that after I'm fetching the Mbtiles file

**Comment by lovasoa** [comment]
The buffer probably doesn't contain a valid sqlite file, but you didn't post the file, nor the code you are using to fetch it.

**Comment by arezhz** [comment]
yes, I say that, the file is the Mbtiles file for the leaflet package.

**Comment by arezhz** [comment]
> The buffer probably doesn't contain a valid sqlite file, but you didn't post the file, nor the code you are using to fetch it.

yes, I say that, the file is the Mbtiles file for the leaflet package.
