### ISSUE TITLE
file is not a database.

### ISSUE THREAD

**Issue by arezhz** [sql-js/sql.js#580]
I have a Mbtiles file and I want to read that with sql.js but when I did run a query, I got an error.

```
function (buffer: ArrayBuffer) {
    initSqlJs({
        locateFile: (file) => `/src/assets/sql/${file}`,
    }).then((SQL) => {
        this._db = new SQL.Database(new Uint8Array(buffer));
        console.log(this._db.exec("select * from map")); // error is here
       }
    })
}
```

buffer: I take that after I'm fetching the Mbtiles file

The file is the Mbtiles file for the leaflet package.

**Comment by lovasoa** [comment]
Please do not open multiple issues with the same question. 

Closing as a duplicate of https://github.com/sql-js/sql.js/issues/579

No valid reproduction showing a bug in sql.js has been shared; I suspect the problem is in your code.
