### ISSUE TITLE
stmt.getAsObject() gives empty object in the latest release (v1.10.3)

### ISSUE THREAD

**Issue by skgadi** [sql-js/sql.js#582]
Until 2 days  back, the following function was working as expected by returning an array of objects.

```js
async function SIG_GetColumnNames(inTableName) {
  const stmt = db.prepare("SELECT * FROM SIG_COL_NAMES WHERE SIG_TAB= '" + inTableName + "' ORDER BY SIG_VIS_ORDER ASC;");
  const rows = [];
  while (stmt.step()) {
    rows.push(stmt.getAsObject());
  }
  return rows;
}
```

Since the update, it is returning an array of empty objects.

**Comment by lovasoa** [comment]
can you provide a self contained reproduction?

**Comment by lovasoa** [comment]
This may not be the cause, but you should not use string concatenation to form your sql statements. Use statement parameters instead.

**Comment by lovasoa** [comment]
You can use https://jsfiddle.net/ to create a self-contained reproduction

**Comment by lovasoa** [comment]
You can use https://jsfiddle.net/ to create a self-contained reproduction

**Comment by skgadi** [comment]
> can you provide a self contained reproduction?

Hi @lovasoa ,

I understood my mistake.

I was importing `sql-wasm.js` from previous version (node_modules) of sql.js and `wasm` from latest version (CDN). Hence obviously its was an error on my part. When I tried to make a standalone program to present here, I found my mistake. Fixing it, it is working as expected. I am sorry to trouble all of you with this issue.

**Comment by lovasoa** [comment]
No, that's the same as above. I mean using the second argument (`params`) to db.prepare. https://sql.js.org/documentation/Database.html

**Comment by skgadi** [comment]
> No, that's the same as above. I mean using the second argument (`params`) to db.prepare. https://sql.js.org/documentation/Database.html

```javascript
async function SIG_GetColumnNames(inTableName) {
  const stmt = db.prepare("SELECT * FROM SIG_COL_NAMES WHERE SIG_TAB= ? ORDER BY SIG_VIS_ORDER ASC;",[inTableName]);
  const rows = [];
  while (stmt.step()) {
    rows.push(stmt.getAsObject());
  }
  return rows;
}
```

Is this a right way to improve performance?
