### ISSUE TITLE
cdn version updated but no new release?

### ISSUE THREAD

**Issue by sjkp** [sql-js/sql.js#590]
The version of sql-wasm.wasm located at https://sql.js.org/dist/sql-wasm.wasm have this md5 sum: f6ad6454f4630b310eb8473858eb33bb

However if i download from npm or from the release page the sql-wasm.wasm have this md5sum: 8f5029a1d3545424d4f25647673e5e32 

What's going on are you updating the cdn, without releasing a new version?  Or maybe the docs should just not point to https://sql.js.org instead you should point to https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.10.3/sql-wasm.wasm or similar so people can pin a specific version.

**Comment by lovasoa** [comment]
sql.js.org always points to the latest development version from github, whereas npm contains the latest release.

I'm making a new release.

**Comment by lovasoa** [comment]
I just pushed v1.11.0 which is compatible with the wasm file from sql.js.org
