### ISSUE TITLE
Memory access out of bounds

### ISSUE THREAD

**Issue by Mark2M** [sql-js/sql.js#592]
I have a svelte app and updated to 1.11.0 this morning. 

I immediately got the memory access out of bounds and can no longer work with SQLite. Rolling back to 1.10.3 fixes the issue for now.

**Comment by lovasoa** [comment]
Are you using matching versions of sql.js and and the bundled wasm file ?
Is there a chance that you updated the js file, but not the wasm ?

If your setup is correct, then a minimal reproduction is welcome !

**Comment by Mark2M** [comment]
I didn't update the wasm file, I'm new to sql.js. 

I'll give it a go and let you know thanks.

**Comment by Mark2M** [comment]
You were right, thanks very much 👍
