### ISSUE TITLE
getAsObject returns undefined object values

### ISSUE THREAD

**Issue by Randy808** [sql-js/sql.js#601]
[Statement.getAsObject](https://sql.js.org/documentation/Statement.html#%5B%22getAsObject%22%5D) returns an object with undefined values when 'opts' (labeled optional) is omitted as an argument. 

Workaround: Pass an empty object as argument

Reproduction steps:
1. Download asm.js version of sql.js from https://github.com/sql-js/sql.js/releases/tag/v1.12.0
2. Link the downloaded sql.js file from any html file
3. Run the following from within the page's context:
```
async function testDb() {
  let config = {};

  let sql = await initSqlJs(config);
  let db = new sql.Database();
  let sqlstr =
    "CREATE TABLE hello (a int, b char); \
INSERT INTO hello VALUES (0, 'hello'); \
INSERT INTO hello VALUES (1, 'world');";

  db.run(sqlstr); // Run the query without returning anything
  stmt = db.prepare("SELECT * FROM hello");
  console.log(stmt.getAsObject());
}
testDb()
```

**Comment by lovasoa** [comment]
You forgot to call stmt.step.

But we could make a better job at explaining this in the documentation ! 

Could you open a small pr updating the docs ?
