### ISSUE TITLE
out of memory and CSP

### ISSUE THREAD

**Issue by firien** [sql-js/sql.js#71]
I have had the code below running for about a year in a WebWorker. It just loops through some tables; creates them, and then downloads and inserts data.
Today I updated sql.js (from master) and it error'd on insertion - complaining that the table did not yet exist. This is from a WebWorker so everything should be synchronous, but it seems like `db.exec()` is not. If I wrap the XHR in a `setTimeout()` I no longer get 'table does not exist' error; instead I get an out of memory error.

``` coffee
for table_name of tables
  t = tables[table_name]
  #create table
  db.exec("CREATE TABLE #{table_name} (#{t.columns.join(',')});")
  #download data
  request = new XMLHttpRequest()
  request.open 'GET', t.url, false
  request.setRequestHeader 'X-Requested-With', 'XMLHttpRequest'
  request.setRequestHeader 'X-CSRF-Token', token
  request.send()
  results = JSON.parse request.responseText
  #insert each result
  results.each t.insert#will error here complaining table does not exist yet.
  this.postMessage {loaded: true, table: table_name, count: results.length}
```

Currently i am using an OLD version of sql.js, I believe i pulled it directly from an old demo site, not from the repo.

CSP:
This old version also does not use `eval` and is compliant with my site's CSP. Do you know how I could compile this so `eval` is omitted from final result?

**Comment by githorse** [comment]
What's the latest on this? Do I need `unsafe-eval` (or maybe now `wasm-unsafe-eval`) in my CSP in order to use sql.js?
